/- This file is generated by gates/assurance-v2-replay.py. -/
import Thermite.AssurancePolicyV2

namespace Thermite.CertificationMetatheory

def generatedConstructorPairLawsV2 : List ConstructorPairLawV2 := [
  ⟨.runtime, .runtime, true, true, [.runtime]⟩,
  ⟨.runtime, .bounded, false, false, []⟩,
  ⟨.runtime, .solverIncomplete, false, false, []⟩,
  ⟨.runtime, .solverComplete, false, false, []⟩,
  ⟨.runtime, .leanEmpirical, false, false, []⟩,
  ⟨.runtime, .leanComplete, false, false, []⟩,
  ⟨.bounded, .runtime, false, false, []⟩,
  ⟨.bounded, .bounded, true, true, [.bounded]⟩,
  ⟨.bounded, .solverIncomplete, false, false, []⟩,
  ⟨.bounded, .solverComplete, false, false, []⟩,
  ⟨.bounded, .leanEmpirical, false, false, []⟩,
  ⟨.bounded, .leanComplete, false, false, []⟩,
  ⟨.solverIncomplete, .runtime, false, false, []⟩,
  ⟨.solverIncomplete, .bounded, false, false, []⟩,
  ⟨.solverIncomplete, .solverIncomplete, true, true, [.solverIncomplete]⟩,
  ⟨.solverIncomplete, .solverComplete, true, false, [.solverIncomplete]⟩,
  ⟨.solverIncomplete, .leanEmpirical, true, false, [.solverIncomplete]⟩,
  ⟨.solverIncomplete, .leanComplete, true, false, [.solverIncomplete]⟩,
  ⟨.solverComplete, .runtime, false, false, []⟩,
  ⟨.solverComplete, .bounded, false, false, []⟩,
  ⟨.solverComplete, .solverIncomplete, false, true, [.solverIncomplete]⟩,
  ⟨.solverComplete, .solverComplete, true, true, [.solverComplete]⟩,
  ⟨.solverComplete, .leanEmpirical, false, false, [.solverIncomplete]⟩,
  ⟨.solverComplete, .leanComplete, true, false, [.solverComplete]⟩,
  ⟨.leanEmpirical, .runtime, false, false, []⟩,
  ⟨.leanEmpirical, .bounded, false, false, []⟩,
  ⟨.leanEmpirical, .solverIncomplete, false, true, [.solverIncomplete]⟩,
  ⟨.leanEmpirical, .solverComplete, false, false, [.solverIncomplete]⟩,
  ⟨.leanEmpirical, .leanEmpirical, true, true, [.leanEmpirical]⟩,
  ⟨.leanEmpirical, .leanComplete, true, false, [.leanEmpirical]⟩,
  ⟨.leanComplete, .runtime, false, false, []⟩,
  ⟨.leanComplete, .bounded, false, false, []⟩,
  ⟨.leanComplete, .solverIncomplete, false, true, [.solverIncomplete]⟩,
  ⟨.leanComplete, .solverComplete, false, true, [.solverComplete]⟩,
  ⟨.leanComplete, .leanEmpirical, false, true, [.leanEmpirical]⟩,
  ⟨.leanComplete, .leanComplete, true, true, [.leanComplete]⟩
]

theorem generated_replay_matches_symbolic_policy :
    generatedConstructorPairLawsV2 = constructorPairLawsV2 := by decide

theorem generated_replay_covers_six_families_and_thirty_six_pairs :
    allAssuranceKindsV2.length = 6 ∧ generatedConstructorPairLawsV2.length = 36 := by
  decide

def omittedLeanCompleteReplay : List ConstructorPairLawV2 :=
  generatedConstructorPairLawsV2.filter fun row =>
    row.left != .leanComplete && row.right != .leanComplete

theorem omitted_family_mutant_is_rejected :
    omittedLeanCompleteReplay ≠ constructorPairLawsV2 := by decide

def missingCommonLowerBoundReplay : List ConstructorPairLawV2 :=
  generatedConstructorPairLawsV2.map fun row =>
    if row.left = .solverComplete && row.right = .leanEmpirical then
      { row with lowerBounds := [] }
    else row

theorem missing_lower_bound_mutant_is_rejected :
    missingCommonLowerBoundReplay ≠ constructorPairLawsV2 := by decide

end Thermite.CertificationMetatheory
