/- This file is generated by gates/assurance-transport-replay.py. -/
import Thermite.AssuranceTransport

namespace Thermite.CertificationMetatheory

def generatedTransportReplayCases : List TransportReplayCase := [
  ⟨"identity", "v1", "v1", .transported, .same, .same, .strengthened⟩,
  ⟨"semantic-expansion", "v1", "v2", .transported, .same, .same, .strengthened⟩,
  ⟨"boundary-weakening", "v2", "v2", .transported, .same, .weaker, .weakened⟩,
  ⟨"semantic-fork", "v1", "fork", .incompatible, .different, .same, .incomparable⟩,
  ⟨"procedure-fork", "lean-v1", "solver-v1", .incompatible, .different, .same, .incomparable⟩,
  ⟨"changed-fiber", "v1", "v2", .transported, .different, .same, .changedFiber⟩,
  ⟨"missing", "v1", "v2", .missing, .same, .same, .missingClassification⟩
]

theorem generated_transport_replay_matches_checked_relation :
    generatedTransportReplayCases.all TransportReplayCase.accepts = true := by
  decide

theorem generated_transport_replay_covers_seven_cases_and_five_outcomes :
    generatedTransportReplayCases.length = 7 ∧
      (generatedTransportReplayCases.map fun row => row.expected).eraseDups.length = 5 := by
  decide

def changedIdentityOutcomeMutant : List TransportReplayCase :=
  generatedTransportReplayCases.map fun row =>
    if row.id = "identity" then { row with expected := .missingClassification } else row

theorem changed_identity_outcome_mutant_is_rejected :
    changedIdentityOutcomeMutant.all TransportReplayCase.accepts = false := by
  decide

end Thermite.CertificationMetatheory
