/- This file is generated by gates/rfc3-certification-replay.py. -/
import Thermite.CertificationPolicy
import Thermite.TcbDischarge

namespace Thermite.CertificationMetatheory

structure CertificationReplayRow where
  id : String
  scope : String
  refutation : String
  residual_trust : String
  discharged_trust : List String
  boundary_kind : String
  boundary_value : String
  model_family : String
  model_version : String
  frame_semantics : String
  frame_version : Nat
  residual_context : String
  classification_fragment : String
  classification_verdict : String
  policy_point : String
  engineer_label : String
deriving DecidableEq, Repr, Inhabited

structure FormalReplayProjection where
  scope : String
  refutation : String
  residual_trust : String
  discharged_trust : List String
  boundary_kind : String
  boundary_value : String
  model_family : String
  model_version : String
  frame_semantics : String
  frame_version : Nat
  residual_context : String
  classification_fragment : String
  classification_verdict : String
  policy_point : String
deriving DecidableEq, Repr

def CertificationReplayRow.formal (row : CertificationReplayRow) : FormalReplayProjection :=
  ⟨row.scope, row.refutation, row.residual_trust, row.discharged_trust,
    row.boundary_kind, row.boundary_value, row.model_family, row.model_version,
    row.frame_semantics, row.frame_version, row.residual_context,
    row.classification_fragment, row.classification_verdict, row.policy_point⟩

def certificationReplaysAs (candidate expected : CertificationReplayRow) : Bool :=
  decide (candidate.formal = expected.formal)

def coherentCertificationCell (row : CertificationReplayRow) : Bool :=
  match row.scope, row.refutation, row.residual_trust with
  | "none", "none", "fiat"
  | "per_execution", "abort", "fiat"
  | "bounded:8", "trace:8", "solver"
  | "all", "incomplete", "solver"
  | "all", "complete", "solver"
  | "all", "empirical", "lean_checked"
  | "all", "complete", "lean_checked" => true
  | _, _, _ => false

def replayRowWellFormed (row : CertificationReplayRow) : Bool :=
  coherentCertificationCell row &&
    (row.boundary_kind == "end_to_end" && row.boundary_value.isEmpty ||
      row.boundary_kind == "to_boundary" && !row.boundary_value.isEmpty ||
      row.boundary_kind == "to_platform" && !row.boundary_value.isEmpty) &&
    row.model_family == "rustc" && row.model_version == "1.95.0" &&
    row.frame_semantics == "thermite-language" && row.frame_version == 1 &&
    ["admitted", "rejected", "unknown"].contains row.classification_verdict &&
    ["runtime", "bounded", "solver_complete", "lean_empirical"].contains row.policy_point

def generatedCertificationReplay : List CertificationReplayRow := [
  {
    id := "no_claim"
    scope := "none"
    refutation := "none"
    residual_trust := "fiat"
    discharged_trust := []
    boundary_kind := "end_to_end"
    boundary_value := ""
    model_family := "rustc"
    model_version := "1.95.0"
    frame_semantics := "thermite-language"
    frame_version := 1
    residual_context := "fiat"
    classification_fragment := "thermite-core-v2"
    classification_verdict := "admitted"
    policy_point := "runtime"
    engineer_label := "no certified claim" },
  {
    id := "runtime"
    scope := "per_execution"
    refutation := "abort"
    residual_trust := "fiat"
    discharged_trust := []
    boundary_kind := "to_boundary"
    boundary_value := "ffi::clock"
    model_family := "rustc"
    model_version := "1.95.0"
    frame_semantics := "thermite-language"
    frame_version := 1
    residual_context := "runtime and platform"
    classification_fragment := "thermite-core-v2"
    classification_verdict := "unknown"
    policy_point := "runtime"
    engineer_label := "checked for this execution" },
  {
    id := "bounded"
    scope := "bounded:8"
    refutation := "trace:8"
    residual_trust := "solver"
    discharged_trust := []
    boundary_kind := "to_platform"
    boundary_value := "x86_64-unknown-linux-gnu"
    model_family := "rustc"
    model_version := "1.95.0"
    frame_semantics := "thermite-language"
    frame_version := 1
    residual_context := "solver and platform"
    classification_fragment := "thermite-core-v2"
    classification_verdict := "rejected"
    policy_point := "bounded"
    engineer_label := "checked through bound 8" },
  {
    id := "incomplete_solver"
    scope := "all"
    refutation := "incomplete"
    residual_trust := "solver"
    discharged_trust := []
    boundary_kind := "end_to_end"
    boundary_value := ""
    model_family := "rustc"
    model_version := "1.95.0"
    frame_semantics := "thermite-language"
    frame_version := 1
    residual_context := "solver"
    classification_fragment := "thermite-core-v2"
    classification_verdict := "admitted"
    policy_point := "solver_complete"
    engineer_label := "proved; failures may be incomplete" },
  {
    id := "complete_solver"
    scope := "all"
    refutation := "complete"
    residual_trust := "solver"
    discharged_trust := ["rustc:1.95.0"]
    boundary_kind := "to_platform"
    boundary_value := "x86_64-unknown-linux-gnu"
    model_family := "rustc"
    model_version := "1.95.0"
    frame_semantics := "thermite-language"
    frame_version := 1
    residual_context := "checker and platform"
    classification_fragment := "thermite-core-v2"
    classification_verdict := "admitted"
    policy_point := "solver_complete"
    engineer_label := "proved with complete counterexamples" },
  {
    id := "empirical_lean"
    scope := "all"
    refutation := "empirical"
    residual_trust := "lean_checked"
    discharged_trust := []
    boundary_kind := "to_boundary"
    boundary_value := "ffi::allocator"
    model_family := "rustc"
    model_version := "1.95.0"
    frame_semantics := "thermite-language"
    frame_version := 1
    residual_context := "kernel and boundary"
    classification_fragment := "thermite-core-v2"
    classification_verdict := "unknown"
    policy_point := "lean_empirical"
    engineer_label := "kernel checked; empirical refutation" },
  {
    id := "complete_lean"
    scope := "all"
    refutation := "complete"
    residual_trust := "lean_checked"
    discharged_trust := ["solver", "rustc:1.95.0"]
    boundary_kind := "end_to_end"
    boundary_value := ""
    model_family := "rustc"
    model_version := "1.95.0"
    frame_semantics := "thermite-language"
    frame_version := 1
    residual_context := "lean kernel"
    classification_fragment := "thermite-core-v2"
    classification_verdict := "admitted"
    policy_point := "lean_empirical"
    engineer_label := "kernel checked for all inputs" }
]

def completeSolverReplay : CertificationReplayRow := generatedCertificationReplay[4]!

theorem every_generated_row_is_formally_well_formed :
    generatedCertificationReplay.all replayRowWellFormed = true := by decide

def authoritativeMutations : List CertificationReplayRow := [
  { completeSolverReplay with scope := "none" },
  { completeSolverReplay with refutation := "incomplete" },
  { completeSolverReplay with residual_trust := "fiat" },
  { completeSolverReplay with discharged_trust := ["engineer-label"] },
  { completeSolverReplay with boundary_kind := "to_boundary" },
  { completeSolverReplay with boundary_value := "engineer-label" },
  { completeSolverReplay with model_family := "engineer-label" },
  { completeSolverReplay with model_version := "1.96.0" },
  { completeSolverReplay with frame_semantics := "engineer-label" },
  { completeSolverReplay with frame_version := 2 },
  { completeSolverReplay with residual_context := "engineer-label" },
  { completeSolverReplay with classification_fragment := "engineer-label" },
  { completeSolverReplay with classification_verdict := "unknown" },
  { completeSolverReplay with policy_point := "lean_empirical" }
]

theorem every_authoritative_mutation_is_rejected :
    authoritativeMutations.all (fun row => !certificationReplaysAs row completeSolverReplay) = true := by
  decide

def relabeledReplay : CertificationReplayRow :=
  { completeSolverReplay with engineer_label := "anything presentational" }

theorem engineer_label_is_non_authoritative :
    certificationReplaysAs relabeledReplay completeSolverReplay = true := by decide

def engineerLabelSubstitutedForFormalScope : CertificationReplayRow :=
  { completeSolverReplay with scope := completeSolverReplay.engineer_label }

theorem engineer_label_formal_substitution_rejected :
    certificationReplaysAs engineerLabelSubstitutedForFormalScope completeSolverReplay = false := by
  decide

end Thermite.CertificationMetatheory
