/- This file is generated by gates/rfc3-certification-replay.py. -/
import Thermite.CertificationReplaySemantics
import Thermite.TcbDischarge

namespace Thermite.CertificationMetatheory

structure CertificationReplayRow where
  id : String
  scope : String
  refutation : String
  residual_trust : String
  discharged_trust : List String
  boundary_kind : String
  boundary_value : String
  model_family : String
  model_version : String
  frame_semantics : String
  frame_version : Nat
  residual_context : String
  classification_fragment : String
  classification_verdict : String
  policy_point : String
  engineer_label : String
deriving DecidableEq, Repr, Inhabited

structure RawReplayProjection where
  scope : String
  refutation : String
  residual_trust : String
  discharged_trust : List String
  boundary_kind : String
  boundary_value : String
  model_family : String
  model_version : String
  frame_semantics : String
  frame_version : Nat
  residual_context : String
  classification_fragment : String
  classification_verdict : String
  policy_point : String
deriving DecidableEq, Repr

def CertificationReplayRow.formal (row : CertificationReplayRow) : RawReplayProjection :=
  ⟨row.scope, row.refutation, row.residual_trust, row.discharged_trust,
    row.boundary_kind, row.boundary_value, row.model_family, row.model_version,
    row.frame_semantics, row.frame_version, row.residual_context,
    row.classification_fragment, row.classification_verdict, row.policy_point⟩

def certificationReplaysAs (candidate expected : CertificationReplayRow) : Bool :=
  decide (candidate.formal = expected.formal)

def generatedCertificationReplay : List CertificationReplayRow := [
  {
    id := "no_claim"
    scope := "none"
    refutation := "none"
    residual_trust := "fiat"
    discharged_trust := []
    boundary_kind := "end_to_end"
    boundary_value := ""
    model_family := "rustc"
    model_version := "1.95.0"
    frame_semantics := "thermite-language"
    frame_version := 1
    residual_context := "fiat"
    classification_fragment := "thermite-core-v2"
    classification_verdict := "admitted"
    policy_point := "runtime"
    engineer_label := "no certified claim" },
  {
    id := "runtime"
    scope := "per_execution"
    refutation := "abort"
    residual_trust := "fiat"
    discharged_trust := []
    boundary_kind := "to_boundary"
    boundary_value := "ffi::clock"
    model_family := "rustc"
    model_version := "1.95.0"
    frame_semantics := "thermite-language"
    frame_version := 1
    residual_context := "runtime and platform"
    classification_fragment := "thermite-core-v2"
    classification_verdict := "unknown"
    policy_point := "runtime"
    engineer_label := "checked for this execution" },
  {
    id := "bounded"
    scope := "bounded:8"
    refutation := "trace:8"
    residual_trust := "solver"
    discharged_trust := []
    boundary_kind := "to_platform"
    boundary_value := "x86_64-unknown-linux-gnu"
    model_family := "rustc"
    model_version := "1.95.0"
    frame_semantics := "thermite-language"
    frame_version := 1
    residual_context := "solver and platform"
    classification_fragment := "thermite-core-v2"
    classification_verdict := "rejected"
    policy_point := "bounded"
    engineer_label := "checked through bound 8" },
  {
    id := "incomplete_solver"
    scope := "all"
    refutation := "incomplete"
    residual_trust := "solver"
    discharged_trust := []
    boundary_kind := "end_to_end"
    boundary_value := ""
    model_family := "rustc"
    model_version := "1.95.0"
    frame_semantics := "thermite-language"
    frame_version := 1
    residual_context := "solver"
    classification_fragment := "thermite-core-v2"
    classification_verdict := "admitted"
    policy_point := "solver_complete"
    engineer_label := "proved; failures may be incomplete" },
  {
    id := "complete_solver"
    scope := "all"
    refutation := "complete"
    residual_trust := "solver"
    discharged_trust := ["rustc:1.95.0"]
    boundary_kind := "to_platform"
    boundary_value := "x86_64-unknown-linux-gnu"
    model_family := "rustc"
    model_version := "1.95.0"
    frame_semantics := "thermite-language"
    frame_version := 1
    residual_context := "checker and platform"
    classification_fragment := "thermite-core-v2"
    classification_verdict := "admitted"
    policy_point := "solver_complete"
    engineer_label := "proved with complete counterexamples" },
  {
    id := "empirical_lean"
    scope := "all"
    refutation := "empirical"
    residual_trust := "lean_checked"
    discharged_trust := []
    boundary_kind := "to_boundary"
    boundary_value := "ffi::allocator"
    model_family := "rustc"
    model_version := "1.95.0"
    frame_semantics := "thermite-language"
    frame_version := 1
    residual_context := "kernel and boundary"
    classification_fragment := "thermite-core-v2"
    classification_verdict := "unknown"
    policy_point := "lean_empirical"
    engineer_label := "kernel checked; empirical refutation" },
  {
    id := "complete_lean"
    scope := "all"
    refutation := "complete"
    residual_trust := "lean_checked"
    discharged_trust := ["solver", "rustc:1.95.0"]
    boundary_kind := "end_to_end"
    boundary_value := ""
    model_family := "rustc"
    model_version := "1.95.0"
    frame_semantics := "thermite-language"
    frame_version := 1
    residual_context := "lean kernel"
    classification_fragment := "thermite-core-v2"
    classification_verdict := "admitted"
    policy_point := "lean_empirical"
    engineer_label := "kernel checked for all inputs" }
]

def semanticProjectionForId : String → Option FormalReplayProjection
  | "no_claim" => some ⟨.noClaim, .none, .none, .fiat, [], .endToEnd,
      rustc195Identity, ⟨"thermite-language", 1⟩, "fiat",
      ⟨"thermite-core", 2⟩, .admitted, .runtime⟩
  | "runtime" => some ⟨.runtime, .perExecution, .abort, .fiat, [],
      .toBoundary "ffi::clock", rustc195Identity, ⟨"thermite-language", 1⟩,
      "runtime and platform", ⟨"thermite-core", 2⟩, .unknown, .runtime⟩
  | "bounded" => some (boundedProjection 8)
  | "incomplete_solver" => some ⟨.incompleteSolver, .all, .incomplete, .solver, [],
      .endToEnd, rustc195Identity, ⟨"thermite-language", 1⟩, "solver",
      ⟨"thermite-core", 2⟩, .admitted, .solverComplete⟩
  | "complete_solver" => some ⟨.completeSolver, .all, .complete, .solver,
      ["rustc:1.95.0"], .toPlatform "x86_64-unknown-linux-gnu", rustc195Identity,
      ⟨"thermite-language", 1⟩, "checker and platform",
      ⟨"thermite-core", 2⟩, .admitted, .solverComplete⟩
  | "empirical_lean" => some ⟨.empiricalLean, .all, .empirical, .leanChecked, [],
      .toBoundary "ffi::allocator", rustc195Identity, ⟨"thermite-language", 1⟩,
      "kernel and boundary", ⟨"thermite-core", 2⟩, .unknown, .leanEmpirical⟩
  | "complete_lean" => some ⟨.completeLean, .all, .complete, .leanChecked,
      ["solver", "rustc:1.95.0"], .endToEnd, rustc195Identity,
      ⟨"thermite-language", 1⟩, "lean kernel",
      ⟨"thermite-core", 2⟩, .admitted, .leanEmpirical⟩
  | _ => none

def expectedRow (id : String) : Option CertificationReplayRow :=
  generatedCertificationReplay.find? (fun row => row.id == id)

/-- Decode succeeds only when every authoritative interchange field equals the
checked canonical row, then returns typed metatheory objects for that family. -/
def decodeCertificationReplay (row : CertificationReplayRow) : Option FormalReplayProjection :=
  match expectedRow row.id, semanticProjectionForId row.id with
  | some expected, some semantic =>
      if row.formal = expected.formal then some semantic else none
  | _, _ => none

def replayRowWellFormed (row : CertificationReplayRow) : Bool :=
  match decodeCertificationReplay row with
  | some semantic => coherentProjection semantic
  | none => false

def completeSolverReplay : CertificationReplayRow := generatedCertificationReplay[4]!

theorem every_generated_row_is_formally_well_formed :
    generatedCertificationReplay.all replayRowWellFormed = true := by decide

theorem generated_rows_cover_every_certification_family :
    generatedCertificationReplay.filterMap
      (fun row => (decodeCertificationReplay row).map FormalReplayProjection.cell) =
      allCertificationCells := by decide

theorem generated_rows_construct_actual_metatheory_objects :
    generatedCertificationReplay.all (fun row =>
      match decodeCertificationReplay row with
      | some semantic =>
          semantic.frame.semantics == "thermite-language" &&
          semantic.model == rustc195Identity &&
          semantic.fragment.version == ⟨"thermite-core", 2⟩ &&
          !semantic.context.name.isEmpty
      | none => false) = true := by decide

def authoritativeMutations : List CertificationReplayRow := [
  { completeSolverReplay with scope := "none" },
  { completeSolverReplay with refutation := "incomplete" },
  { completeSolverReplay with residual_trust := "fiat" },
  { completeSolverReplay with discharged_trust := ["engineer-label"] },
  { completeSolverReplay with boundary_kind := "to_boundary" },
  { completeSolverReplay with boundary_value := "engineer-label" },
  { completeSolverReplay with model_family := "engineer-label" },
  { completeSolverReplay with model_version := "1.96.0" },
  { completeSolverReplay with frame_semantics := "engineer-label" },
  { completeSolverReplay with frame_version := 2 },
  { completeSolverReplay with residual_context := "engineer-label" },
  { completeSolverReplay with classification_fragment := "engineer-label" },
  { completeSolverReplay with classification_verdict := "unknown" },
  { completeSolverReplay with policy_point := "lean_empirical" }
]

theorem every_authoritative_mutation_is_rejected :
    authoritativeMutations.all (fun row => (decodeCertificationReplay row).isNone) = true := by
  decide

def relabeledReplay : CertificationReplayRow :=
  { completeSolverReplay with engineer_label := "anything presentational" }

theorem engineer_label_is_non_authoritative :
    decodeCertificationReplay relabeledReplay = decodeCertificationReplay completeSolverReplay := by decide

def engineerLabelSubstitutedForFormalScope : CertificationReplayRow :=
  { completeSolverReplay with scope := completeSolverReplay.engineer_label }

theorem engineer_label_formal_substitution_rejected :
    decodeCertificationReplay engineerLabelSubstitutedForFormalScope = none := by
  decide

end Thermite.CertificationMetatheory
