/- This file is generated by gates/organization-policy-replay.py. -/
import Thermite.OrganizationPolicy

namespace Thermite.CertificationMetatheory

inductive OrganizationReplayOutcome where
  | passed | excepted | failed | rejected
deriving DecidableEq, Repr

structure OrganizationReplayCase where
  id : String
  exactScope : Bool
  checkedNormalization : Bool
  delegatedOwner : Bool
  liftsPresent : Bool
  floorDominated : Bool
  exceptionActive : Bool
  conflictFree : Bool
  expected : OrganizationReplayOutcome
deriving DecidableEq, Repr

def classifyOrganizationReplay (row : OrganizationReplayCase) : OrganizationReplayOutcome :=
  if !row.exactScope || !row.checkedNormalization || !row.delegatedOwner || !row.conflictFree then
    .rejected
  else if row.liftsPresent && row.floorDominated then .passed
  else if row.exceptionActive then .excepted
  else .failed

def OrganizationReplayCase.accepts (row : OrganizationReplayCase) : Bool :=
  decide (classifyOrganizationReplay row = row.expected)

def generatedOrganizationReplayCases : List OrganizationReplayCase := [
  ⟨"exact-floor", true, true, true, true, true, false, true, .passed⟩,
  ⟨"active-exception", true, true, true, true, false, true, true, .excepted⟩,
  ⟨"expired-exception", true, true, true, true, false, false, true, .failed⟩,
  ⟨"missing-project-lift", true, true, true, false, true, false, true, .failed⟩,
  ⟨"missing-repository", false, true, true, true, true, false, true, .rejected⟩,
  ⟨"schema-skew", true, false, true, true, true, false, true, .rejected⟩,
  ⟨"policy-skew-no-transport", true, false, true, true, true, false, true, .rejected⟩,
  ⟨"undelegated-owner", true, true, false, true, true, false, true, .rejected⟩,
  ⟨"incomparable-inheritance", true, true, true, true, true, false, false, .rejected⟩,
  ⟨"forged-package", false, true, true, true, true, false, true, .rejected⟩,
  ⟨"empty-population", true, true, true, false, false, false, true, .failed⟩,
  ⟨"checked-policy-normalization", true, true, true, true, true, false, true, .passed⟩
]

theorem generated_organization_replay_matches_policy :
    generatedOrganizationReplayCases.all OrganizationReplayCase.accepts = true := by
  decide

theorem generated_organization_replay_covers_twelve_cases_and_four_outcomes :
    generatedOrganizationReplayCases.length = 12 ∧
      (generatedOrganizationReplayCases.map fun row => row.expected).eraseDups.length = 4 := by
  decide

end Thermite.CertificationMetatheory
