/- This file is generated by gates/assurance-policy-migration-replay.py. -/
import Thermite.PolicyMigration

namespace Thermite.CertificationMetatheory

inductive PolicyMigrationReplayRelation where
  | compatible | informationLoss | incompatible | missing
deriving DecidableEq, Repr

inductive PolicyMigrationReplayDirection where
  | forward | reverse | equal | misbound
deriving DecidableEq, Repr

inductive PolicyMigrationReplayOutcome where
  | compared | policySkew
deriving DecidableEq, Repr

structure PolicyMigrationReplayCase where
  id : String
  relation : PolicyMigrationReplayRelation
  direction : PolicyMigrationReplayDirection
  complete : Bool
  orderIsomorphism : Bool
  receiptBound : Bool
  expected : PolicyMigrationReplayOutcome
deriving DecidableEq, Repr

def classifyPolicyMigrationReplay (row : PolicyMigrationReplayCase) :
    PolicyMigrationReplayOutcome :=
  if row.relation = .compatible && row.direction = .forward && row.complete &&
      row.orderIsomorphism && row.receiptBound then .compared else .policySkew

def PolicyMigrationReplayCase.accepts (row : PolicyMigrationReplayCase) : Bool :=
  decide (classifyPolicyMigrationReplay row = row.expected)

def generatedPolicyMigrationReplayCases : List PolicyMigrationReplayCase := [
  ⟨"compatible", .compatible, .forward, true, true, true, .compared⟩,
  ⟨"missing", .missing, .forward, false, false, false, .policySkew⟩,
  ⟨"information-loss", .informationLoss, .forward, true, false, true, .policySkew⟩,
  ⟨"incompatible", .incompatible, .forward, true, false, true, .policySkew⟩,
  ⟨"reverse", .compatible, .reverse, true, true, true, .policySkew⟩,
  ⟨"equal-version", .compatible, .equal, true, true, true, .policySkew⟩,
  ⟨"misbound-endpoints", .compatible, .misbound, true, true, true, .policySkew⟩,
  ⟨"incomplete-families", .compatible, .forward, false, true, true, .policySkew⟩,
  ⟨"non-order-isomorphism", .compatible, .forward, true, false, true, .policySkew⟩,
  ⟨"forged-receipt", .compatible, .forward, true, true, false, .policySkew⟩
]

theorem generated_policy_migration_replay_matches_checked_relation :
    generatedPolicyMigrationReplayCases.all PolicyMigrationReplayCase.accepts = true := by
  decide

theorem generated_policy_migration_replay_covers_ten_cases_and_two_outcomes :
    generatedPolicyMigrationReplayCases.length = 10 ∧
      (generatedPolicyMigrationReplayCases.map fun row => row.expected).eraseDups.length = 2 := by
  decide

def forgedReceiptAcceptedMutant : List PolicyMigrationReplayCase :=
  generatedPolicyMigrationReplayCases.map fun row =>
    if row.id = "forged-receipt" then { row with expected := .compared } else row

theorem forged_receipt_accepted_mutant_is_rejected :
    forgedReceiptAcceptedMutant.all PolicyMigrationReplayCase.accepts = false := by
  decide

end Thermite.CertificationMetatheory
