/- This file is generated by gates/workspace-assurance-replay.py. -/
import Thermite.WorkspaceComposition

namespace Thermite.CertificationMetatheory

inductive WorkspaceReplayOutcome where
  | wholeWorkspace | acceptedSubset | rejected
deriving DecidableEq, Repr

structure WorkspaceReplayCase where
  id : String
  planExact : Bool
  coordinatesUnique : Bool
  allReports : Bool
  itemsExact : Bool
  allProjectLifts : Bool
  nonempty : Bool
  expected : WorkspaceReplayOutcome
deriving DecidableEq, Repr

def classifyWorkspaceReplay (row : WorkspaceReplayCase) : WorkspaceReplayOutcome :=
  if !row.planExact || !row.coordinatesUnique || !row.itemsExact then .rejected
  else if row.allReports && row.allProjectLifts && row.nonempty then .wholeWorkspace
  else .acceptedSubset

def WorkspaceReplayCase.accepts (row : WorkspaceReplayCase) : Bool :=
  decide (classifyWorkspaceReplay row = row.expected)

def generatedWorkspaceReplayCases : List WorkspaceReplayCase := [
  ⟨"complete-two-package-matrix", true, true, true, true, true, true, .wholeWorkspace⟩,
  ⟨"missing-package-report", true, true, false, true, true, true, .acceptedSubset⟩,
  ⟨"missing-target-report", true, true, false, true, true, true, .acceptedSubset⟩,
  ⟨"feature-cell-misbound", false, true, true, true, true, true, .rejected⟩,
  ⟨"platform-cell-misbound", false, true, true, true, true, true, .rejected⟩,
  ⟨"generated-source-omitted", false, true, true, true, true, true, .rejected⟩,
  ⟨"planned-item-omitted", true, true, true, false, true, true, .rejected⟩,
  ⟨"duplicate-matrix-cell", true, false, true, true, true, true, .rejected⟩,
  ⟨"empty-workspace", true, true, true, true, true, false, .acceptedSubset⟩,
  ⟨"missing-project-lift", true, true, true, true, false, true, .acceptedSubset⟩
]

theorem generated_workspace_replay_matches_checked_composition :
    generatedWorkspaceReplayCases.all WorkspaceReplayCase.accepts = true := by
  decide

theorem generated_workspace_replay_covers_ten_cases_and_three_outcomes :
    generatedWorkspaceReplayCases.length = 10 ∧
      (generatedWorkspaceReplayCases.map fun row => row.expected).eraseDups.length = 3 := by
  decide

def omittedItemAcceptedMutant : List WorkspaceReplayCase :=
  generatedWorkspaceReplayCases.map fun row =>
    if row.id = "planned-item-omitted" then { row with expected := .wholeWorkspace } else row

theorem omitted_item_accepted_mutant_is_rejected :
    omittedItemAcceptedMutant.all WorkspaceReplayCase.accepts = false := by
  decide

end Thermite.CertificationMetatheory
