use crate::capability::{CapabilityKind, Rights};

/// Exact operation count for the immutable v1 profile. Additions require a new
/// registry version instead of silently widening the accepted platform.
pub const X86_64_PC_UEFI_SMP_V1_OPERATION_COUNT: usize = 104;

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum PlatformDomain {
    Boot,
    Memory,
    Mmio,
    Pio,
    Irq,
    Cpu,
    Atomic,
    Smp,
    Dma,
    Clock,
    Entropy,
    Power,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PlatformOperation {
    key: &'static str,
    pub signature: &'static str,
    pub contract: &'static str,
    pub domain: PlatformDomain,
    pub capability: Option<CapabilityKind>,
    pub rights: Rights,
    pub symbol: &'static str,
    pub source_contract_sha256: Option<&'static str>,
    pub source_reachable: bool,
    pub secondary_domains: &'static [PlatformDomain],
    pub abi: &'static str,
    pub alignment: u16,
    pub ownership: &'static str,
    pub model: &'static str,
    pub concurrency: &'static str,
    pub failure: &'static str,
    pub evidence: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RegistryError {
    UnknownName,
    DuplicateName,
    SignatureDrift,
    ContractDrift,
    DomainDrift,
    CapabilityDrift,
    RightsDrift,
    SymbolDrift,
    SourceContractDrift,
    ReachabilityDrift,
    MetadataDrift,
}

impl PlatformOperation {
    #[must_use]
    pub fn name(&self) -> &'static str {
        canonical_name(self.key)
    }

    pub fn exact_match(&self, candidate: &Self) -> Result<(), RegistryError> {
        if self.key != candidate.key {
            return Err(RegistryError::UnknownName);
        }
        if self.signature != candidate.signature {
            return Err(RegistryError::SignatureDrift);
        }
        if self.contract != candidate.contract {
            return Err(RegistryError::ContractDrift);
        }
        if self.domain != candidate.domain {
            return Err(RegistryError::DomainDrift);
        }
        if self.capability != candidate.capability {
            return Err(RegistryError::CapabilityDrift);
        }
        if self.rights != candidate.rights {
            return Err(RegistryError::RightsDrift);
        }
        if self.symbol != candidate.symbol {
            return Err(RegistryError::SymbolDrift);
        }
        if self.source_contract_sha256 != candidate.source_contract_sha256 {
            return Err(RegistryError::SourceContractDrift);
        }
        if self.source_reachable != candidate.source_reachable {
            return Err(RegistryError::ReachabilityDrift);
        }
        if self.secondary_domains != candidate.secondary_domains
            || self.abi != candidate.abi
            || self.alignment != candidate.alignment
            || self.ownership != candidate.ownership
            || self.model != candidate.model
            || self.concurrency != candidate.concurrency
            || self.failure != candidate.failure
            || self.evidence != candidate.evidence
        {
            return Err(RegistryError::MetadataDrift);
        }
        Ok(())
    }
}

pub fn lookup(name: &str) -> Result<&'static PlatformOperation, RegistryError> {
    let mut found = None;
    for entry in X86_64_PC_UEFI_SMP_V1 {
        if entry.name() == name {
            if found.is_some() {
                return Err(RegistryError::DuplicateName);
            }
            found = Some(entry);
        }
    }
    found.ok_or(RegistryError::UnknownName)
}

const NONE: Option<CapabilityKind> = None;
const BOOT: Option<CapabilityKind> = Some(CapabilityKind::BootInfo);
const CPU: Option<CapabilityKind> = Some(CapabilityKind::Cpu);
const CPU_SET: Option<CapabilityKind> = Some(CapabilityKind::CpuSet);
const CPU_LOCAL: Option<CapabilityKind> = Some(CapabilityKind::CpuLocal);
const PHYS: Option<CapabilityKind> = Some(CapabilityKind::PhysRegion);
const FRAME: Option<CapabilityKind> = Some(CapabilityKind::Frame);
const SPACE: Option<CapabilityKind> = Some(CapabilityKind::AddressSpace);
const VIRT: Option<CapabilityKind> = Some(CapabilityKind::VirtRegion);
const MMIO: Option<CapabilityKind> = Some(CapabilityKind::Mmio);
const PIO: Option<CapabilityKind> = Some(CapabilityKind::IoPort);
const IRQ: Option<CapabilityKind> = Some(CapabilityKind::Irq);
const IRQ_STATE: Option<CapabilityKind> = Some(CapabilityKind::IrqState);
const TRAP: Option<CapabilityKind> = Some(CapabilityKind::TrapFrame);
const USER: Option<CapabilityKind> = Some(CapabilityKind::UserContext);
const DMA: Option<CapabilityKind> = Some(CapabilityKind::Dma);
const IOMMU: Option<CapabilityKind> = Some(CapabilityKind::IommuDomain);
const CLOCK: Option<CapabilityKind> = Some(CapabilityKind::Clock);
const ENTROPY: Option<CapabilityKind> = Some(CapabilityKind::Entropy);
const POWER: Option<CapabilityKind> = Some(CapabilityKind::Power);

/// The first frozen platform registry. Contracts are compact identifiers here;
/// the image receipt binds their full Thermite source and SHA-256 digest.
pub static X86_64_PC_UEFI_SMP_V1: &[PlatformOperation] = &[
    op(
        "boot.handoff",
        "fn(BootInfo)->BootBytes",
        "bounded_handoff",
        PlatformDomain::Boot,
        BOOT,
        Rights::READ,
        "tpl_boot_handoff",
    ),
    op(
        "memory.frame_split",
        "fn(Frame,u64)->(Frame,Frame)",
        "partition_exact",
        PlatformDomain::Memory,
        FRAME,
        Rights::TRANSFER,
        "tpl_frame_split",
    ),
    op(
        "memory.frame_join",
        "fn(Frame,Frame)->Frame",
        "adjacent_join",
        PlatformDomain::Memory,
        FRAME,
        Rights::TRANSFER,
        "tpl_frame_join",
    ),
    op(
        "memory.frame_zero",
        "fn(Frame)->Frame",
        "zero_exact",
        PlatformDomain::Memory,
        FRAME,
        Rights::WRITE,
        "tpl_frame_zero",
    ),
    op(
        "memory.frame_query",
        "fn(Frame)->FrameInfo",
        "query_exact_generation",
        PlatformDomain::Memory,
        FRAME,
        Rights::READ,
        "tpl_frame_query",
    ),
    op(
        "memory.frame_lend",
        "fn(Frame,u32)->Frame",
        "consume_generation_to_borrower",
        PlatformDomain::Memory,
        FRAME,
        Rights::TRANSFER,
        "tpl_frame_lend",
    ),
    op(
        "memory.frame_reclaim",
        "fn(Frame,u32)->Frame",
        "matching_borrower_next_generation",
        PlatformDomain::Memory,
        FRAME,
        Rights::TRANSFER,
        "tpl_frame_reclaim",
    ),
    op(
        "memory.temporary_map",
        "fn(VirtRegion,Frame)->TemporaryMapping",
        "bounded_window_generation",
        PlatformDomain::Memory,
        VIRT,
        Rights::MAP,
        "tpl_temporary_map",
    ),
    op(
        "memory.temporary_revoke",
        "fn(VirtRegion,TemporaryMapping)->()",
        "revoke_exact_generation",
        PlatformDomain::Memory,
        VIRT,
        Rights::MAP,
        "tpl_temporary_revoke",
    ),
    op(
        "memory.space_create",
        "fn(AddressSpace)->AddressSpace",
        "fresh_inactive_root",
        PlatformDomain::Memory,
        SPACE,
        Rights::CONTROL,
        "tpl_space_create",
    ),
    op(
        "memory.map",
        "fn(AddressSpace,Frame,MapRequest)->Mapping",
        "map_cap_bounded",
        PlatformDomain::Memory,
        SPACE,
        Rights::MAP,
        "tpl_map",
    ),
    op(
        "memory.unmap",
        "fn(AddressSpace,u64)->Mapping",
        "unmap_exact",
        PlatformDomain::Memory,
        SPACE,
        Rights::MAP,
        "tpl_unmap",
    ),
    op(
        "memory.protect",
        "fn(AddressSpace,u64,Perm)->()",
        "protect_exact",
        PlatformDomain::Memory,
        SPACE,
        Rights::MAP,
        "tpl_protect",
    ),
    op(
        "memory.activate",
        "fn(AddressSpace)->()",
        "activate_root",
        PlatformDomain::Memory,
        SPACE,
        Rights::CONTROL,
        "tpl_activate",
    ),
    op(
        "memory.inspect",
        "fn(AddressSpace,u64)->Result<Mapping>",
        "inspect_exact_mapping",
        PlatformDomain::Memory,
        SPACE,
        Rights::READ,
        "tpl_space_inspect",
    ),
    op(
        "memory.destroy",
        "fn(AddressSpace)->()",
        "inactive_empty_consume_root",
        PlatformDomain::Memory,
        SPACE,
        Rights::CONTROL,
        "tpl_space_destroy",
    ),
    op(
        "memory.translation_validate",
        "fn(u64,PageSize,Perm,CachePolicy)->Result",
        "canonical_aligned_profile_translation",
        PlatformDomain::Memory,
        NONE,
        Rights::empty(),
        "tpl_translation_validate",
    ),
    op(
        "memory.tlb_local",
        "fn(AddressSpace,u64)->()",
        "invalidate_local",
        PlatformDomain::Memory,
        SPACE,
        Rights::MAP,
        "tpl_tlb_local",
    ),
    op(
        "memory.tlb_space",
        "fn(AddressSpace)->()",
        "invalidate_active_space",
        PlatformDomain::Memory,
        SPACE,
        Rights::MAP,
        "tpl_tlb_space",
    ),
    op(
        "memory.user_copy_in",
        "fn(AddressSpace,u64,&mut[u8])->Result",
        "copy_all_or_fault",
        PlatformDomain::Memory,
        SPACE,
        Rights::READ,
        "tpl_user_copy_in",
    ),
    op(
        "memory.user_copy_out",
        "fn(AddressSpace,u64,&[u8])->Result",
        "copy_all_or_fault",
        PlatformDomain::Memory,
        SPACE,
        Rights::WRITE,
        "tpl_user_copy_out",
    ),
    op(
        "mmio.read8",
        "fn(Mmio,u64)->u8",
        "aligned_in_range",
        PlatformDomain::Mmio,
        MMIO,
        Rights::READ,
        "tpl_mmio_read8",
    ),
    op(
        "mmio.read16",
        "fn(Mmio,u64)->u16",
        "aligned_in_range",
        PlatformDomain::Mmio,
        MMIO,
        Rights::READ,
        "tpl_mmio_read16",
    ),
    op(
        "mmio.read32",
        "fn(Mmio,u64)->u32",
        "aligned_in_range",
        PlatformDomain::Mmio,
        MMIO,
        Rights::READ,
        "tpl_mmio_read32",
    ),
    op(
        "mmio.read64",
        "fn(Mmio,u64)->u64",
        "aligned_in_range",
        PlatformDomain::Mmio,
        MMIO,
        Rights::READ,
        "tpl_mmio_read64",
    ),
    op(
        "mmio.write8",
        "fn(Mmio,u64,u8)->()",
        "aligned_in_range",
        PlatformDomain::Mmio,
        MMIO,
        Rights::WRITE,
        "tpl_mmio_write8",
    ),
    op(
        "mmio.write16",
        "fn(Mmio,u64,u16)->()",
        "aligned_in_range",
        PlatformDomain::Mmio,
        MMIO,
        Rights::WRITE,
        "tpl_mmio_write16",
    ),
    op(
        "mmio.write32",
        "fn(Mmio,u64,u32)->()",
        "aligned_in_range",
        PlatformDomain::Mmio,
        MMIO,
        Rights::WRITE,
        "tpl_mmio_write32",
    ),
    op(
        "mmio.write64",
        "fn(Mmio,u64,u64)->()",
        "aligned_in_range",
        PlatformDomain::Mmio,
        MMIO,
        Rights::WRITE,
        "tpl_mmio_write64",
    ),
    op(
        "pio.read8",
        "fn(IoPort,u16)->u8",
        "port_in_range",
        PlatformDomain::Pio,
        PIO,
        Rights::READ,
        "tpl_pio_read8",
    ),
    op(
        "pio.read16",
        "fn(IoPort,u16)->u16",
        "port_in_range",
        PlatformDomain::Pio,
        PIO,
        Rights::READ,
        "tpl_pio_read16",
    ),
    op(
        "pio.read32",
        "fn(IoPort,u16)->u32",
        "port_in_range",
        PlatformDomain::Pio,
        PIO,
        Rights::READ,
        "tpl_pio_read32",
    ),
    op(
        "pio.write8",
        "fn(IoPort,u16,u8)->()",
        "port_in_range",
        PlatformDomain::Pio,
        PIO,
        Rights::WRITE,
        "tpl_pio_write8",
    ),
    op(
        "pio.write16",
        "fn(IoPort,u16,u16)->()",
        "port_in_range",
        PlatformDomain::Pio,
        PIO,
        Rights::WRITE,
        "tpl_pio_write16",
    ),
    op(
        "pio.write32",
        "fn(IoPort,u16,u32)->()",
        "port_in_range",
        PlatformDomain::Pio,
        PIO,
        Rights::WRITE,
        "tpl_pio_write32",
    ),
    op(
        "mmio.compiler_fence",
        "fn()->()",
        "compiler_ordering_barrier",
        PlatformDomain::Mmio,
        NONE,
        Rights::empty(),
        "tpl_mmio_compiler_fence",
    ),
    op(
        "mmio.read_barrier",
        "fn()->()",
        "device_reads_before_after",
        PlatformDomain::Mmio,
        NONE,
        Rights::empty(),
        "tpl_mmio_read_barrier",
    ),
    op(
        "mmio.write_barrier",
        "fn()->()",
        "device_writes_before_after",
        PlatformDomain::Mmio,
        NONE,
        Rights::empty(),
        "tpl_mmio_write_barrier",
    ),
    op(
        "mmio.full_barrier",
        "fn()->()",
        "device_full_ordering_barrier",
        PlatformDomain::Mmio,
        NONE,
        Rights::empty(),
        "tpl_mmio_full_barrier",
    ),
    op(
        "pio.pci_config",
        "fn(IoPort,PciAddress,u32,Option<u32>)->u32",
        "bounded_pci_configuration",
        PlatformDomain::Pio,
        PIO,
        Rights::READ.union(Rights::WRITE),
        "tpl_pci_config",
    ),
    op(
        "mmio.feature_query",
        "fn(Mmio,u32)->FeatureRecord",
        "bounded_device_feature_record",
        PlatformDomain::Mmio,
        MMIO,
        Rights::READ,
        "tpl_device_feature_query",
    ),
    op(
        "irq.save_disable",
        "fn(CpuLocal)->IrqState",
        "cpu_local_generation",
        PlatformDomain::Irq,
        CPU_LOCAL,
        Rights::CONTROL,
        "tpl_irq_save_disable",
    ),
    op(
        "irq.restore",
        "fn(CpuLocal,IrqState)->()",
        "matching_cpu_generation",
        PlatformDomain::Irq,
        CPU_LOCAL,
        Rights::CONTROL,
        "tpl_irq_restore",
    ),
    op(
        "irq.mask",
        "fn(Irq)->()",
        "mask_owned_route",
        PlatformDomain::Irq,
        IRQ,
        Rights::CONTROL,
        "tpl_irq_mask",
    ),
    op(
        "irq.unmask",
        "fn(Irq)->()",
        "unmask_owned_route",
        PlatformDomain::Irq,
        IRQ,
        Rights::CONTROL,
        "tpl_irq_unmask",
    ),
    op(
        "irq.route",
        "fn(Irq,Cpu,u8)->()",
        "route_owned_vector",
        PlatformDomain::Irq,
        IRQ,
        Rights::ROUTE,
        "tpl_irq_route",
    ),
    op(
        "irq.eoi",
        "fn(Irq,u8)->()",
        "ack_owned_vector",
        PlatformDomain::Irq,
        IRQ,
        Rights::CONTROL,
        "tpl_irq_eoi",
    ),
    op(
        "irq.state_validate",
        "fn(IrqState,CpuLocal)->Result",
        "matching_cpu_single_use_generation",
        PlatformDomain::Irq,
        IRQ_STATE,
        Rights::CONTROL,
        "tpl_irq_state_validate",
    ),
    op(
        "cpu.logical_id",
        "fn(Cpu)->u16",
        "stable_logical_id",
        PlatformDomain::Cpu,
        CPU,
        Rights::READ,
        "tpl_cpu_logical_id",
    ),
    op(
        "cpu.features",
        "fn(Cpu)->FeatureBits",
        "profile_subset",
        PlatformDomain::Cpu,
        CPU,
        Rights::READ,
        "tpl_cpu_features",
    ),
    op(
        "cpu.control_state",
        "fn(Cpu)->ControlState",
        "profile_masked_control_registers",
        PlatformDomain::Cpu,
        CPU,
        Rights::READ,
        "tpl_cpu_control_state",
    ),
    op(
        "cpu.msr_read",
        "fn(Cpu,u32)->u64",
        "allowlisted_model_specific_register",
        PlatformDomain::Cpu,
        CPU,
        Rights::READ,
        "tpl_cpu_msr_read",
    ),
    op(
        "cpu.msr_write",
        "fn(Cpu,u32,u64)->()",
        "allowlisted_model_specific_register",
        PlatformDomain::Cpu,
        CPU,
        Rights::CONTROL,
        "tpl_cpu_msr_write",
    ),
    op(
        "cpu.supported_widths",
        "fn(Cpu)->WidthRecord",
        "page_and_atomic_width_subset",
        PlatformDomain::Cpu,
        CPU,
        Rights::READ,
        "tpl_cpu_supported_widths",
    ),
    op(
        "cpu.install_gdt",
        "fn(CpuLocal,DescriptorTable)->()",
        "checked_gdt_install",
        PlatformDomain::Cpu,
        CPU_LOCAL,
        Rights::CONTROL,
        "tpl_cpu_install_gdt",
    ),
    op(
        "cpu.install_idt",
        "fn(CpuLocal,DescriptorTable)->()",
        "checked_idt_install",
        PlatformDomain::Cpu,
        CPU_LOCAL,
        Rights::CONTROL,
        "tpl_cpu_install_idt",
    ),
    op(
        "cpu.install_tss",
        "fn(CpuLocal,TssDescriptor)->()",
        "checked_per_cpu_tss_install",
        PlatformDomain::Cpu,
        CPU_LOCAL,
        Rights::CONTROL,
        "tpl_cpu_install_tss",
    ),
    op(
        "cpu.install_syscall",
        "fn(CpuLocal,SyscallDescriptor)->()",
        "checked_syscall_msr_install",
        PlatformDomain::Cpu,
        CPU_LOCAL,
        Rights::CONTROL,
        "tpl_cpu_install_syscall",
    ),
    op(
        "cpu.install_local",
        "fn(Cpu,CpuLocal)->()",
        "install_once",
        PlatformDomain::Cpu,
        CPU_LOCAL,
        Rights::CONTROL,
        "tpl_cpu_install_local",
    ),
    op(
        "cpu.enter_context",
        "fn(Cpu,UserContext)->!",
        "exact_context_transition",
        PlatformDomain::Cpu,
        CPU,
        Rights::CONTROL,
        "tpl_enter_context",
    ),
    op(
        "cpu.trap_construct",
        "fn(TrapFrame,TrapInput)->TrapRecord",
        "checked_trap_origin_and_frame",
        PlatformDomain::Cpu,
        TRAP,
        Rights::CONTROL,
        "tpl_trap_construct",
    ),
    op(
        "cpu.context_switch",
        "fn(UserContext,UserContext)->()",
        "unique_context_owner_transition",
        PlatformDomain::Cpu,
        USER,
        Rights::CONTROL,
        "tpl_context_switch",
    ),
    op(
        "cpu.return_kernel",
        "fn(TrapFrame)->!",
        "exact_kernel_return_frame",
        PlatformDomain::Cpu,
        TRAP,
        Rights::CONTROL,
        "tpl_return_kernel",
    ),
    op(
        "cpu.return_user",
        "fn(UserContext)->!",
        "exact_user_return_frame",
        PlatformDomain::Cpu,
        USER,
        Rights::CONTROL,
        "tpl_return_user",
    ),
    op(
        "cpu.pause",
        "fn(Cpu)->()",
        "bounded_spin_hint",
        PlatformDomain::Cpu,
        CPU,
        Rights::CONTROL,
        "tpl_cpu_pause",
    ),
    op(
        "cpu.halt_interruptible",
        "fn(Cpu)->()",
        "interrupt_aware_idle",
        PlatformDomain::Cpu,
        CPU,
        Rights::CONTROL,
        "tpl_cpu_halt_interruptible",
    ),
    op(
        "cpu.rendezvous",
        "fn(Cpu,u64)->()",
        "bounded_architecture_rendezvous",
        PlatformDomain::Cpu,
        CPU,
        Rights::CONTROL,
        "tpl_cpu_rendezvous",
    ),
    op(
        "atomic.load",
        "fn(Atomic,Ordering)->u64",
        "legal_load_order",
        PlatformDomain::Atomic,
        PHYS,
        Rights::READ,
        "tpl_atomic_load",
    ),
    op(
        "atomic.store",
        "fn(Atomic,u64,Ordering)->()",
        "legal_store_order",
        PlatformDomain::Atomic,
        PHYS,
        Rights::WRITE,
        "tpl_atomic_store",
    ),
    op(
        "atomic.swap",
        "fn(Atomic,u64,Ordering)->u64",
        "modification_order",
        PlatformDomain::Atomic,
        PHYS,
        Rights::READ.union(Rights::WRITE),
        "tpl_atomic_swap",
    ),
    op(
        "atomic.compare_exchange",
        "fn(Atomic,u64,u64,Ordering,Ordering)->Cas",
        "legal_cas_orders",
        PlatformDomain::Atomic,
        PHYS,
        Rights::READ.union(Rights::WRITE),
        "tpl_atomic_compare_exchange",
    ),
    op(
        "atomic.compare_exchange_weak",
        "fn(Atomic,u64,u64,Ordering,Ordering)->Cas",
        "legal_cas_orders_and_spurious_failure",
        PlatformDomain::Atomic,
        PHYS,
        Rights::READ.union(Rights::WRITE),
        "tpl_atomic_compare_exchange_weak",
    ),
    op(
        "atomic.fetch",
        "fn(Atomic,FetchOp,u64,Ordering)->u64",
        "modification_order",
        PlatformDomain::Atomic,
        PHYS,
        Rights::READ.union(Rights::WRITE),
        "tpl_atomic_fetch",
    ),
    op(
        "atomic.compiler_fence",
        "fn(Ordering)->()",
        "legal_compiler_fence_order",
        PlatformDomain::Atomic,
        NONE,
        Rights::empty(),
        "tpl_atomic_compiler_fence",
    ),
    op(
        "atomic.hardware_fence",
        "fn(Ordering)->()",
        "legal_hardware_fence_order",
        PlatformDomain::Atomic,
        NONE,
        Rights::empty(),
        "tpl_atomic_hardware_fence",
    ),
    op(
        "smp.discover",
        "fn(CpuSet)->Topology",
        "unique_stable_ids",
        PlatformDomain::Smp,
        CPU_SET,
        Rights::READ,
        "tpl_smp_discover",
    ),
    op(
        "smp.start",
        "fn(Cpu,CpuLocal)->StartResult",
        "monotonic_lifecycle",
        PlatformDomain::Smp,
        CPU,
        Rights::CONTROL,
        "tpl_smp_start",
    ),
    op(
        "smp.ipi",
        "fn(CpuSet,u8,u64)->()",
        "epoch_targets_exact",
        PlatformDomain::Smp,
        CPU_SET,
        Rights::CONTROL,
        "tpl_smp_ipi",
    ),
    op(
        "smp.rendezvous",
        "fn(CpuSet,u64)->AckMask",
        "epoch_ack_exact",
        PlatformDomain::Smp,
        CPU_SET,
        Rights::CONTROL,
        "tpl_smp_rendezvous",
    ),
    op(
        "smp.online_snapshot",
        "fn(CpuSet)->OnlineSnapshot",
        "release_acquire_online_mask",
        PlatformDomain::Smp,
        CPU_SET,
        Rights::READ,
        "tpl_smp_online_snapshot",
    ),
    op(
        "smp.stop_request",
        "fn(CpuSet,u64)->AckMask",
        "epoch_correlated_stop_ack",
        PlatformDomain::Smp,
        CPU_SET,
        Rights::CONTROL,
        "tpl_smp_stop_request",
    ),
    op(
        "smp.shootdown",
        "fn(CpuSet,u64,u64,u64)->AckMask",
        "mapping_epoch_exact",
        PlatformDomain::Smp,
        CPU_SET,
        Rights::CONTROL,
        "tpl_smp_shootdown",
    ),
    op(
        "dma.pin",
        "fn(Dma,PhysRegion)->DmaMapping",
        "device_domain_generation",
        PlatformDomain::Dma,
        DMA,
        Rights::TRANSFER,
        "tpl_dma_pin",
    ),
    op(
        "dma.domain_create",
        "fn(IommuDomain,Device,Aperture)->Domain",
        "device_aperture_exact",
        PlatformDomain::Dma,
        IOMMU,
        Rights::MAP,
        "tpl_dma_domain_create",
    ),
    op(
        "dma.map",
        "fn(IommuDomain,DmaMapping,u64)->Segments",
        "iommu_or_identity_domain_exact",
        PlatformDomain::Dma,
        IOMMU,
        Rights::MAP,
        "tpl_dma_map",
    ),
    op(
        "dma.segments",
        "fn(DmaMapping)->Segments",
        "device_visible_segments_exact",
        PlatformDomain::Dma,
        DMA,
        Rights::READ,
        "tpl_dma_segments",
    ),
    op(
        "dma.sync",
        "fn(DmaMapping,Direction)->()",
        "coherence_transition",
        PlatformDomain::Dma,
        DMA,
        Rights::CONTROL,
        "tpl_dma_sync",
    ),
    op(
        "dma.unmap",
        "fn(IommuDomain,DmaMapping)->Segments",
        "consume_domain_mapping",
        PlatformDomain::Dma,
        IOMMU,
        Rights::MAP,
        "tpl_dma_unmap",
    ),
    op(
        "dma.unpin",
        "fn(DmaMapping)->()",
        "consume_generation",
        PlatformDomain::Dma,
        DMA,
        Rights::TRANSFER,
        "tpl_dma_unpin",
    ),
    source_op(
        op(
            "clock.read",
            "fn(Clock)->Instant",
            "monotonic_with_error",
            PlatformDomain::Clock,
            CLOCK,
            Rights::READ,
            "tpl_clock_read",
        ),
        // RE-PINNED 2026-08-08 for RFC-17 (one vocabulary). The digest is sha256 over
        // `format!("{:#?}", contract)`, and `Debug` renders FIELD NAMES, so renaming
        // Contract's fields moves it even though no clause, span or effect changed.
        // This is a case RFC-17 §3 said did not exist — the rename is type-directed
        // everywhere the COMPILER can see, and a digest over a Debug rendering is
        // exactly where it cannot.
        // prior (RFC-6 full-word surface): 3f525f14dd2f058197d170ff40cffb2f7a363368ccbdbc5f60775c72851eb444
        // RE-PINNED 2026-08-06 for RFC-6 (full words). This digest is sha256 over
        // `format!("{:#?}", contract)`, which carries clause SPANS, so migrating
        // conformance/bootable_kernel.th moves it even though the contract's
        // meaning is unchanged — the AST fingerprint over item names, clause text
        // and the effect row is identical before and after.
        // prior (Thermite 2 surface): 2a1b32cc68f553037a9d886f1d87aef36120a4a1b96b49534eb334e4ea62378c
        "756cd3895ca4c825b1b163ee168b6106887071c2f52e8d9dbe3f3891672898b6",
    ),
    op(
        "clock.arm",
        "fn(Clock,Cpu,u64)->()",
        "per_cpu_deadline",
        PlatformDomain::Clock,
        CLOCK,
        Rights::CONTROL,
        "tpl_clock_arm",
    ),
    op(
        "clock.cancel",
        "fn(Clock,Cpu)->()",
        "cancel_current_per_cpu_deadline",
        PlatformDomain::Clock,
        CLOCK,
        Rights::CONTROL,
        "tpl_clock_cancel",
    ),
    op(
        "entropy.fill",
        "fn(Entropy,&mut[u8])->Result",
        "exact_or_failure",
        PlatformDomain::Entropy,
        ENTROPY,
        Rights::READ,
        "tpl_entropy_fill",
    ),
    op(
        "power.reboot",
        "fn(Power)->!",
        "terminal_reboot",
        PlatformDomain::Power,
        POWER,
        Rights::CONTROL,
        "tpl_power_reboot",
    ),
    op(
        "power.off",
        "fn(Power)->!",
        "terminal_poweroff",
        PlatformDomain::Power,
        POWER,
        Rights::CONTROL,
        "tpl_power_off",
    ),
    op(
        "power.halt",
        "fn(Power)->!",
        "terminal_halt",
        PlatformDomain::Power,
        POWER,
        Rights::CONTROL,
        "tpl_power_halt",
    ),
    op(
        "runtime.memcpy",
        "fn(*mut u8,*const u8,usize)->*mut u8",
        "exact_nonoverlap",
        PlatformDomain::Boot,
        NONE,
        Rights::empty(),
        "memcpy",
    ),
    op(
        "runtime.memmove",
        "fn(*mut u8,*const u8,usize)->*mut u8",
        "exact_overlap",
        PlatformDomain::Boot,
        NONE,
        Rights::empty(),
        "memmove",
    ),
    op(
        "runtime.memset",
        "fn(*mut u8,u8,usize)->*mut u8",
        "exact_fill",
        PlatformDomain::Boot,
        NONE,
        Rights::empty(),
        "memset",
    ),
    op(
        "runtime.panic",
        "fn(PanicInfo)->!",
        "terminal_named_panic",
        PlatformDomain::Boot,
        NONE,
        Rights::empty(),
        "tpl_runtime_panic",
    ),
    op(
        "runtime.contract_violation",
        "fn(ContractFailure)->!",
        "terminal_named_contract_failure",
        PlatformDomain::Boot,
        NONE,
        Rights::empty(),
        "tpl_contract_violation",
    ),
    op(
        "runtime.allocation_failure",
        "fn(Layout)->!",
        "terminal_named_allocation_failure",
        PlatformDomain::Boot,
        NONE,
        Rights::empty(),
        "tpl_allocation_failure",
    ),
    op(
        "runtime.stack_probe",
        "fn(usize)->()",
        "bounded_stack_probe",
        PlatformDomain::Boot,
        NONE,
        Rights::empty(),
        "tpl_stack_probe",
    ),
    op(
        "runtime.terminal_fault",
        "fn(FaultRecord)->!",
        "terminal_named_platform_fault",
        PlatformDomain::Boot,
        NONE,
        Rights::empty(),
        "tpl_terminal_fault",
    ),
];

const fn op(
    key: &'static str,
    signature: &'static str,
    contract: &'static str,
    domain: PlatformDomain,
    capability: Option<CapabilityKind>,
    rights: Rights,
    symbol: &'static str,
) -> PlatformOperation {
    PlatformOperation {
        key,
        signature,
        contract,
        domain,
        capability,
        rights,
        symbol,
        source_contract_sha256: None,
        source_reachable: false,
        secondary_domains: &[],
        abi: "C",
        alignment: 1,
        ownership: "capability-generation-preserved-unless-contract-consumes",
        model: contract,
        concurrency: "registry-model-defined",
        failure: "typed-platform-error-or-declared-terminal",
        evidence: "model-tests+symbol-inventory+qemu-transcript",
    }
}

const fn source_op(
    mut operation: PlatformOperation,
    source_contract_sha256: &'static str,
) -> PlatformOperation {
    operation.source_contract_sha256 = Some(source_contract_sha256);
    operation.source_reachable = true;
    operation
}

fn canonical_name(key: &str) -> &'static str {
    match key {
        "boot.handoff" => "kernel::boot::handoff@v1",
        "memory.frame_split" => "kernel::memory::frame_split@v1",
        "memory.frame_join" => "kernel::memory::frame_join@v1",
        "memory.frame_zero" => "kernel::memory::frame_zero@v1",
        "memory.frame_query" => "kernel::memory::frame_query@v1",
        "memory.frame_lend" => "kernel::memory::frame_lend@v1",
        "memory.frame_reclaim" => "kernel::memory::frame_reclaim@v1",
        "memory.temporary_map" => "kernel::memory::temporary_map@v1",
        "memory.temporary_revoke" => "kernel::memory::temporary_revoke@v1",
        "memory.space_create" => "kernel::memory::space_create@v1",
        "memory.map" => "kernel::memory::map@v1",
        "memory.unmap" => "kernel::memory::unmap@v1",
        "memory.protect" => "kernel::memory::protect@v1",
        "memory.activate" => "kernel::memory::activate@v1",
        "memory.inspect" => "kernel::memory::inspect@v1",
        "memory.destroy" => "kernel::memory::destroy@v1",
        "memory.translation_validate" => "kernel::memory::translation_validate@v1",
        "memory.tlb_local" => "kernel::memory::tlb_local@v1",
        "memory.tlb_space" => "kernel::memory::tlb_space@v1",
        "memory.user_copy_in" => "kernel::memory::user_copy_in@v1",
        "memory.user_copy_out" => "kernel::memory::user_copy_out@v1",
        "mmio.read8" => "kernel::mmio::read8@v1",
        "mmio.read16" => "kernel::mmio::read16@v1",
        "mmio.read32" => "kernel::mmio::read32@v1",
        "mmio.read64" => "kernel::mmio::read64@v1",
        "mmio.write8" => "kernel::mmio::write8@v1",
        "mmio.write16" => "kernel::mmio::write16@v1",
        "mmio.write32" => "kernel::mmio::write32@v1",
        "mmio.write64" => "kernel::mmio::write64@v1",
        "mmio.compiler_fence" => "kernel::mmio::compiler_fence@v1",
        "mmio.read_barrier" => "kernel::mmio::read_barrier@v1",
        "mmio.write_barrier" => "kernel::mmio::write_barrier@v1",
        "mmio.full_barrier" => "kernel::mmio::full_barrier@v1",
        "mmio.feature_query" => "kernel::mmio::feature_query@v1",
        "pio.read8" => "kernel::pio::read8@v1",
        "pio.read16" => "kernel::pio::read16@v1",
        "pio.read32" => "kernel::pio::read32@v1",
        "pio.write8" => "kernel::pio::write8@v1",
        "pio.write16" => "kernel::pio::write16@v1",
        "pio.write32" => "kernel::pio::write32@v1",
        "pio.pci_config" => "kernel::pio::pci_config@v1",
        "irq.save_disable" => "kernel::irq::save_disable@v1",
        "irq.restore" => "kernel::irq::restore@v1",
        "irq.mask" => "kernel::irq::mask@v1",
        "irq.unmask" => "kernel::irq::unmask@v1",
        "irq.route" => "kernel::irq::route@v1",
        "irq.eoi" => "kernel::irq::eoi@v1",
        "irq.state_validate" => "kernel::irq::state_validate@v1",
        "cpu.logical_id" => "kernel::cpu::logical_id@v1",
        "cpu.features" => "kernel::cpu::features@v1",
        "cpu.control_state" => "kernel::cpu::control_state@v1",
        "cpu.msr_read" => "kernel::cpu::msr_read@v1",
        "cpu.msr_write" => "kernel::cpu::msr_write@v1",
        "cpu.supported_widths" => "kernel::cpu::supported_widths@v1",
        "cpu.install_gdt" => "kernel::cpu::install_gdt@v1",
        "cpu.install_idt" => "kernel::cpu::install_idt@v1",
        "cpu.install_tss" => "kernel::cpu::install_tss@v1",
        "cpu.install_syscall" => "kernel::cpu::install_syscall@v1",
        "cpu.install_local" => "kernel::cpu::install_local@v1",
        "cpu.enter_context" => "kernel::cpu::enter_context@v1",
        "cpu.trap_construct" => "kernel::cpu::trap_construct@v1",
        "cpu.context_switch" => "kernel::cpu::context_switch@v1",
        "cpu.return_kernel" => "kernel::cpu::return_kernel@v1",
        "cpu.return_user" => "kernel::cpu::return_user@v1",
        "cpu.pause" => "kernel::cpu::pause@v1",
        "cpu.halt_interruptible" => "kernel::cpu::halt_interruptible@v1",
        "cpu.rendezvous" => "kernel::cpu::rendezvous@v1",
        "atomic.load" => "kernel::atomic::load@v1",
        "atomic.store" => "kernel::atomic::store@v1",
        "atomic.swap" => "kernel::atomic::swap@v1",
        "atomic.compare_exchange" => "kernel::atomic::compare_exchange@v1",
        "atomic.compare_exchange_weak" => "kernel::atomic::compare_exchange_weak@v1",
        "atomic.fetch" => "kernel::atomic::fetch@v1",
        "atomic.compiler_fence" => "kernel::atomic::compiler_fence@v1",
        "atomic.hardware_fence" => "kernel::atomic::hardware_fence@v1",
        "smp.discover" => "kernel::smp::discover@v1",
        "smp.start" => "kernel::smp::start@v1",
        "smp.ipi" => "kernel::smp::ipi@v1",
        "smp.rendezvous" => "kernel::smp::rendezvous@v1",
        "smp.online_snapshot" => "kernel::smp::online_snapshot@v1",
        "smp.stop_request" => "kernel::smp::stop_request@v1",
        "smp.shootdown" => "kernel::smp::shootdown@v1",
        "dma.pin" => "kernel::dma::pin@v1",
        "dma.domain_create" => "kernel::dma::domain_create@v1",
        "dma.map" => "kernel::dma::map@v1",
        "dma.segments" => "kernel::dma::segments@v1",
        "dma.sync" => "kernel::dma::sync@v1",
        "dma.unmap" => "kernel::dma::unmap@v1",
        "dma.unpin" => "kernel::dma::unpin@v1",
        "clock.read" => "kernel::clock::read@v1",
        "clock.arm" => "kernel::clock::arm@v1",
        "clock.cancel" => "kernel::clock::cancel@v1",
        "entropy.fill" => "kernel::entropy::fill@v1",
        "power.reboot" => "kernel::power::reboot@v1",
        "power.off" => "kernel::power::off@v1",
        "power.halt" => "kernel::power::halt@v1",
        "runtime.memcpy" => "kernel::boot::memcpy@v1",
        "runtime.memmove" => "kernel::boot::memmove@v1",
        "runtime.memset" => "kernel::boot::memset@v1",
        "runtime.panic" => "kernel::boot::panic@v1",
        "runtime.contract_violation" => "kernel::boot::contract_violation@v1",
        "runtime.allocation_failure" => "kernel::boot::allocation_failure@v1",
        "runtime.stack_probe" => "kernel::boot::stack_probe@v1",
        "runtime.terminal_fault" => "kernel::boot::terminal_fault@v1",
        _ => "kernel::invalid@v1",
    }
}
