#!/usr/bin/env python3
"""Validate the checked cross-version/procedure assurance replay matrix."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

MATRIX = "gates/assurance-transport-replay.json"
LEAN = "lean/Thermite/AssuranceTransportReplay.lean"
OUTCOMES = {
    "strengthened",
    "weakened",
    "incomparable",
    "changed_fiber",
    "missing_classification",
}


def canonical(value: object) -> bytes:
    return json.dumps(value, separators=(",", ":"), sort_keys=True).encode()


def classify(case: dict[str, str]) -> str:
    if case["relation"] == "missing":
        return "missing_classification"
    if case["relation"] == "incompatible":
        return "incomparable"
    if case["fiber"] != "same":
        return "changed_fiber"
    if case["boundary"] == "weaker":
        return "weakened"
    return "strengthened"


def lean_constructor(value: str) -> str:
    pieces = value.split("_")
    return "." + pieces[0] + "".join(piece.title() for piece in pieces[1:])


def generated(cases: list[dict[str, str]]) -> str:
    rows = []
    for case in cases:
        rows.append(
            "  ⟨"
            f"{json.dumps(case['id'])}, {json.dumps(case['source'])}, "
            f"{json.dumps(case['target'])}, {lean_constructor(case['relation'])}, "
            f"{lean_constructor(case['fiber'])}, {lean_constructor(case['boundary'])}, "
            f"{lean_constructor(case['outcome'])}⟩"
        )
    body = ",\n".join(rows)
    return f'''/- This file is generated by gates/assurance-transport-replay.py. -/
import Thermite.AssuranceTransport

namespace Thermite.CertificationMetatheory

def generatedTransportReplayCases : List TransportReplayCase := [
{body}
]

theorem generated_transport_replay_matches_checked_relation :
    generatedTransportReplayCases.all TransportReplayCase.accepts = true := by
  decide

theorem generated_transport_replay_covers_seven_cases_and_five_outcomes :
    generatedTransportReplayCases.length = 7 ∧
      (generatedTransportReplayCases.map fun row => row.expected).eraseDups.length = 5 := by
  decide

def changedIdentityOutcomeMutant : List TransportReplayCase :=
  generatedTransportReplayCases.map fun row =>
    if row.id = "identity" then {{ row with expected := .missingClassification }} else row

theorem changed_identity_outcome_mutant_is_rejected :
    changedIdentityOutcomeMutant.all TransportReplayCase.accepts = false := by
  decide

end Thermite.CertificationMetatheory
'''


def validate(root: Path) -> list[str]:
    data = json.loads((root / MATRIX).read_text(encoding="utf-8"))
    errors: list[str] = []
    if data.get("version") != 1:
        errors.append("matrix version must be 1")
    if set(data.get("outcomes", [])) != OUTCOMES:
        errors.append("matrix outcomes must cover the exact five transport outcomes")
    cases = data.get("case")
    if not isinstance(cases, list) or len(cases) != 7:
        errors.append("matrix must contain exactly seven named cases")
        return errors
    ids = [case.get("id") for case in cases]
    if len(set(ids)) != len(ids):
        errors.append("case IDs must be unique")
    for case in cases:
        if classify(case) != case.get("outcome"):
            errors.append(f"{case.get('id')}: outcome does not match checked rule")
    if {case["outcome"] for case in cases} != OUTCOMES:
        errors.append("cases must exercise every transport outcome")
    first = hashlib.sha256(canonical(data)).hexdigest()
    second = hashlib.sha256(canonical(json.loads(canonical(data)))).hexdigest()
    if first != second:
        errors.append("canonical replay is not byte-stable")
    expected_lean = generated(cases)
    target = root / LEAN
    if not target.exists() or target.read_text(encoding="utf-8") != expected_lean:
        errors.append(f"{LEAN} is stale; run gates/assurance-transport-replay.py --write")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    try:
        data = json.loads((root / MATRIX).read_text(encoding="utf-8"))
        if args.write:
            structural_errors = []
            cases = data.get("case")
            if not isinstance(cases, list) or len(cases) != 7:
                structural_errors.append("matrix must contain exactly seven named cases")
            if structural_errors:
                errors = structural_errors
            else:
                (root / LEAN).write_text(generated(cases), encoding="utf-8")
                errors = validate(root)
        else:
            errors = validate(root)
    except (OSError, UnicodeDecodeError, json.JSONDecodeError, KeyError, TypeError) as error:
        print(f"Assurance transport replay: INCONCLUSIVE: {error}", file=sys.stderr)
        return 3
    if errors:
        print("Assurance transport replay: FAIL", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1
    print("Assurance transport replay: clean: 7 cases, 5 outcomes, canonical bytes stable")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
