#!/usr/bin/env python3
"""Validate and generate the policy-version migration replay matrix."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

MATRIX = "gates/assurance-policy-migration-replay.json"
LEAN = "lean/Thermite/PolicyMigrationReplay.lean"
RELATIONS = {"compatible", "information_loss", "incompatible", "missing"}
DIRECTIONS = {"forward", "reverse", "equal", "misbound"}
OUTCOMES = {"compared", "policy_skew"}


def canonical(value: object) -> bytes:
    return json.dumps(value, separators=(",", ":"), sort_keys=True).encode()


def classify(case: dict[str, object]) -> str:
    if (
        case["relation"] == "compatible"
        and case["direction"] == "forward"
        and case["complete"] is True
        and case["order_isomorphism"] is True
        and case["receipt_bound"] is True
    ):
        return "compared"
    return "policy_skew"


def lean_constructor(value: str) -> str:
    pieces = value.split("_")
    return "." + pieces[0] + "".join(piece.title() for piece in pieces[1:])


def generated(cases: list[dict[str, object]]) -> str:
    rows = []
    for case in cases:
        rows.append(
            "  ⟨"
            f"{json.dumps(case['id'])}, {lean_constructor(str(case['relation']))}, "
            f"{lean_constructor(str(case['direction']))}, "
            f"{str(case['complete']).lower()}, "
            f"{str(case['order_isomorphism']).lower()}, "
            f"{str(case['receipt_bound']).lower()}, "
            f"{lean_constructor(str(case['outcome']))}⟩"
        )
    body = ",\n".join(rows)
    return f'''/- This file is generated by gates/assurance-policy-migration-replay.py. -/
import Thermite.PolicyMigration

namespace Thermite.CertificationMetatheory

inductive PolicyMigrationReplayRelation where
  | compatible | informationLoss | incompatible | missing
deriving DecidableEq, Repr

inductive PolicyMigrationReplayDirection where
  | forward | reverse | equal | misbound
deriving DecidableEq, Repr

inductive PolicyMigrationReplayOutcome where
  | compared | policySkew
deriving DecidableEq, Repr

structure PolicyMigrationReplayCase where
  id : String
  relation : PolicyMigrationReplayRelation
  direction : PolicyMigrationReplayDirection
  complete : Bool
  orderIsomorphism : Bool
  receiptBound : Bool
  expected : PolicyMigrationReplayOutcome
deriving DecidableEq, Repr

def classifyPolicyMigrationReplay (row : PolicyMigrationReplayCase) :
    PolicyMigrationReplayOutcome :=
  if row.relation = .compatible && row.direction = .forward && row.complete &&
      row.orderIsomorphism && row.receiptBound then .compared else .policySkew

def PolicyMigrationReplayCase.accepts (row : PolicyMigrationReplayCase) : Bool :=
  decide (classifyPolicyMigrationReplay row = row.expected)

def generatedPolicyMigrationReplayCases : List PolicyMigrationReplayCase := [
{body}
]

theorem generated_policy_migration_replay_matches_checked_relation :
    generatedPolicyMigrationReplayCases.all PolicyMigrationReplayCase.accepts = true := by
  decide

theorem generated_policy_migration_replay_covers_ten_cases_and_two_outcomes :
    generatedPolicyMigrationReplayCases.length = 10 ∧
      (generatedPolicyMigrationReplayCases.map fun row => row.expected).eraseDups.length = 2 := by
  decide

def forgedReceiptAcceptedMutant : List PolicyMigrationReplayCase :=
  generatedPolicyMigrationReplayCases.map fun row =>
    if row.id = "forged-receipt" then {{ row with expected := .compared }} else row

theorem forged_receipt_accepted_mutant_is_rejected :
    forgedReceiptAcceptedMutant.all PolicyMigrationReplayCase.accepts = false := by
  decide

end Thermite.CertificationMetatheory
'''


def validate(root: Path) -> list[str]:
    data = json.loads((root / MATRIX).read_text(encoding="utf-8"))
    errors: list[str] = []
    if data.get("version") != 1:
        errors.append("matrix version must be 1")
    if set(data.get("outcomes", [])) != OUTCOMES:
        errors.append("matrix outcomes must cover compared and policy_skew")
    cases = data.get("case")
    if not isinstance(cases, list) or len(cases) != 10:
        errors.append("matrix must contain exactly ten named cases")
        return errors
    ids = [case.get("id") for case in cases]
    if len(set(ids)) != len(ids):
        errors.append("case IDs must be unique")
    if {case.get("relation") for case in cases} != RELATIONS:
        errors.append("cases must exercise every relation disposition")
    if {case.get("direction") for case in cases} != DIRECTIONS:
        errors.append("cases must exercise every direction disposition")
    for case in cases:
        if classify(case) != case.get("outcome"):
            errors.append(f"{case.get('id')}: outcome does not match checked rule")
    if sum(case.get("outcome") == "compared" for case in cases) != 1:
        errors.append("exactly one fully checked case may compare")
    digest = hashlib.sha256(canonical(data)).hexdigest()
    if digest != hashlib.sha256(canonical(json.loads(canonical(data)))).hexdigest():
        errors.append("canonical replay is not byte-stable")
    target = root / LEAN
    if not target.exists() or target.read_text(encoding="utf-8") != generated(cases):
        errors.append(f"{LEAN} is stale; run {Path(__file__).name} --write")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    try:
        data = json.loads((root / MATRIX).read_text(encoding="utf-8"))
        cases = data.get("case")
        if args.write and isinstance(cases, list):
            (root / LEAN).write_text(generated(cases), encoding="utf-8")
        errors = validate(root)
    except (OSError, UnicodeDecodeError, json.JSONDecodeError, KeyError, TypeError) as error:
        print(f"Assurance policy migration replay: INCONCLUSIVE: {error}", file=sys.stderr)
        return 3
    if errors:
        print("Assurance policy migration replay: FAIL", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1
    print("Assurance policy migration replay: clean: 10 cases, 2 outcomes, canonical bytes stable")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
