#!/usr/bin/env python3
"""Validate and generate the organization formal-policy replay."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

MATRIX = "gates/organization-policy-replay.json"
LEAN = "lean/Thermite/OrganizationPolicyReplay.lean"
OUTCOMES = {"passed", "excepted", "failed", "rejected"}
FIELDS = (
    "exact_scope", "checked_normalization", "delegated_owner", "lifts_present",
    "floor_dominated", "exception_active", "conflict_free",
)


def classify(case: dict[str, object]) -> str:
    if not all(case[field] is True for field in FIELDS[:3]) or case["conflict_free"] is not True:
        return "rejected"
    if case["lifts_present"] is True and case["floor_dominated"] is True:
        return "passed"
    if case["exception_active"] is True:
        return "excepted"
    return "failed"


def generated(cases: list[dict[str, object]]) -> str:
    rows = []
    for case in cases:
        flags = ", ".join(str(case[field]).lower() for field in FIELDS)
        rows.append(f'  ⟨{json.dumps(case["id"])}, {flags}, .{case["outcome"]}⟩')
    body = ",\n".join(rows)
    return f'''/- This file is generated by gates/organization-policy-replay.py. -/
import Thermite.OrganizationPolicy

namespace Thermite.CertificationMetatheory

inductive OrganizationReplayOutcome where
  | passed | excepted | failed | rejected
deriving DecidableEq, Repr

structure OrganizationReplayCase where
  id : String
  exactScope : Bool
  checkedNormalization : Bool
  delegatedOwner : Bool
  liftsPresent : Bool
  floorDominated : Bool
  exceptionActive : Bool
  conflictFree : Bool
  expected : OrganizationReplayOutcome
deriving DecidableEq, Repr

def classifyOrganizationReplay (row : OrganizationReplayCase) : OrganizationReplayOutcome :=
  if !row.exactScope || !row.checkedNormalization || !row.delegatedOwner || !row.conflictFree then
    .rejected
  else if row.liftsPresent && row.floorDominated then .passed
  else if row.exceptionActive then .excepted
  else .failed

def OrganizationReplayCase.accepts (row : OrganizationReplayCase) : Bool :=
  decide (classifyOrganizationReplay row = row.expected)

def generatedOrganizationReplayCases : List OrganizationReplayCase := [
{body}
]

theorem generated_organization_replay_matches_policy :
    generatedOrganizationReplayCases.all OrganizationReplayCase.accepts = true := by
  decide

theorem generated_organization_replay_covers_twelve_cases_and_four_outcomes :
    generatedOrganizationReplayCases.length = 12 ∧
      (generatedOrganizationReplayCases.map fun row => row.expected).eraseDups.length = 4 := by
  decide

end Thermite.CertificationMetatheory
'''


def validate(root: Path) -> list[str]:
    data = json.loads((root / MATRIX).read_text(encoding="utf-8"))
    errors: list[str] = []
    cases = data.get("case", [])
    if data.get("version") != 1 or set(data.get("outcomes", [])) != OUTCOMES:
        errors.append("matrix version/outcomes are invalid")
    if not isinstance(cases, list) or len(cases) != 12:
        return errors + ["matrix must contain exactly twelve cases"]
    if len({case.get("id") for case in cases}) != len(cases):
        errors.append("case IDs must be unique")
    for case in cases:
        if classify(case) != case.get("outcome"):
            errors.append(f"{case.get('id')}: outcome does not match checked rule")
    if {case.get("outcome") for case in cases} != OUTCOMES:
        errors.append("cases must exercise all four outcomes")
    if (root / LEAN).read_text(encoding="utf-8") != generated(cases):
        errors.append(f"{LEAN} is stale; run {Path(__file__).name} --write")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    cases = json.loads((root / MATRIX).read_text(encoding="utf-8"))["case"]
    if args.write:
        (root / LEAN).write_text(generated(cases), encoding="utf-8")
    errors = validate(root)
    if errors:
        print("\n".join(f"organization-policy-replay: {error}" for error in errors), file=sys.stderr)
        return 1
    print(f"organization-policy-replay: {len(cases)} checked cases")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
