#!/usr/bin/env python3
"""Generate and check the shared Rust/Lean RFC-3 AC-10 replay boundary."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

MATRIX = "gates/rfc3-certification-replay.json"
LEAN = "lean/Thermite/CertificationReplay.lean"
FIELDS = [
    "scope", "refutation", "residual_trust", "discharged_trust",
    "boundary_kind", "boundary_value", "model_family", "model_version",
    "frame_semantics", "frame_version", "residual_context",
    "classification_fragment", "classification_verdict", "policy_point",
]


def lean_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def lean_list(values: list[str]) -> str:
    return "[" + ", ".join(lean_string(value) for value in values) + "]"


def row_expr(row: dict[str, object]) -> str:
    parts = []
    for field in ["id", *FIELDS, "engineer_label"]:
        value = row[field]
        rendered = str(value) if isinstance(value, int) else lean_list(value) if isinstance(value, list) else lean_string(value)
        parts.append(f"    {field} := {rendered}")
    return "  {\n" + "\n".join(parts) + " }"


def generated(rows: list[dict[str, object]]) -> str:
    values = ",\n".join(row_expr(row) for row in rows)
    return f'''/- This file is generated by gates/rfc3-certification-replay.py. -/
import Thermite.CertificationPolicy
import Thermite.TcbDischarge

namespace Thermite.CertificationMetatheory

structure CertificationReplayRow where
  id : String
  scope : String
  refutation : String
  residual_trust : String
  discharged_trust : List String
  boundary_kind : String
  boundary_value : String
  model_family : String
  model_version : String
  frame_semantics : String
  frame_version : Nat
  residual_context : String
  classification_fragment : String
  classification_verdict : String
  policy_point : String
  engineer_label : String
deriving DecidableEq, Repr, Inhabited

structure FormalReplayProjection where
  scope : String
  refutation : String
  residual_trust : String
  discharged_trust : List String
  boundary_kind : String
  boundary_value : String
  model_family : String
  model_version : String
  frame_semantics : String
  frame_version : Nat
  residual_context : String
  classification_fragment : String
  classification_verdict : String
  policy_point : String
deriving DecidableEq, Repr

def CertificationReplayRow.formal (row : CertificationReplayRow) : FormalReplayProjection :=
  ⟨row.scope, row.refutation, row.residual_trust, row.discharged_trust,
    row.boundary_kind, row.boundary_value, row.model_family, row.model_version,
    row.frame_semantics, row.frame_version, row.residual_context,
    row.classification_fragment, row.classification_verdict, row.policy_point⟩

def certificationReplaysAs (candidate expected : CertificationReplayRow) : Bool :=
  decide (candidate.formal = expected.formal)

def coherentCertificationCell (row : CertificationReplayRow) : Bool :=
  match row.scope, row.refutation, row.residual_trust with
  | "none", "none", "fiat"
  | "per_execution", "abort", "fiat"
  | "bounded:8", "trace:8", "solver"
  | "all", "incomplete", "solver"
  | "all", "complete", "solver"
  | "all", "empirical", "lean_checked"
  | "all", "complete", "lean_checked" => true
  | _, _, _ => false

def replayRowWellFormed (row : CertificationReplayRow) : Bool :=
  coherentCertificationCell row &&
    (row.boundary_kind == "end_to_end" && row.boundary_value.isEmpty ||
      row.boundary_kind == "to_boundary" && !row.boundary_value.isEmpty ||
      row.boundary_kind == "to_platform" && !row.boundary_value.isEmpty) &&
    row.model_family == "rustc" && row.model_version == "1.95.0" &&
    row.frame_semantics == "thermite-language" && row.frame_version == 1 &&
    ["admitted", "rejected", "unknown"].contains row.classification_verdict &&
    ["runtime", "bounded", "solver_complete", "lean_empirical"].contains row.policy_point

def generatedCertificationReplay : List CertificationReplayRow := [
{values}
]

def completeSolverReplay : CertificationReplayRow := generatedCertificationReplay[4]!

theorem every_generated_row_is_formally_well_formed :
    generatedCertificationReplay.all replayRowWellFormed = true := by decide

def authoritativeMutations : List CertificationReplayRow := [
  {{ completeSolverReplay with scope := "none" }},
  {{ completeSolverReplay with refutation := "incomplete" }},
  {{ completeSolverReplay with residual_trust := "fiat" }},
  {{ completeSolverReplay with discharged_trust := ["engineer-label"] }},
  {{ completeSolverReplay with boundary_kind := "to_boundary" }},
  {{ completeSolverReplay with boundary_value := "engineer-label" }},
  {{ completeSolverReplay with model_family := "engineer-label" }},
  {{ completeSolverReplay with model_version := "1.96.0" }},
  {{ completeSolverReplay with frame_semantics := "engineer-label" }},
  {{ completeSolverReplay with frame_version := 2 }},
  {{ completeSolverReplay with residual_context := "engineer-label" }},
  {{ completeSolverReplay with classification_fragment := "engineer-label" }},
  {{ completeSolverReplay with classification_verdict := "unknown" }},
  {{ completeSolverReplay with policy_point := "lean_empirical" }}
]

theorem every_authoritative_mutation_is_rejected :
    authoritativeMutations.all (fun row => !certificationReplaysAs row completeSolverReplay) = true := by
  decide

def relabeledReplay : CertificationReplayRow :=
  {{ completeSolverReplay with engineer_label := "anything presentational" }}

theorem engineer_label_is_non_authoritative :
    certificationReplaysAs relabeledReplay completeSolverReplay = true := by decide

def engineerLabelSubstitutedForFormalScope : CertificationReplayRow :=
  {{ completeSolverReplay with scope := completeSolverReplay.engineer_label }}

theorem engineer_label_formal_substitution_rejected :
    certificationReplaysAs engineerLabelSubstitutedForFormalScope completeSolverReplay = false := by
  decide

end Thermite.CertificationMetatheory
'''


def validate(root: Path, data: dict[str, object]) -> list[str]:
    errors: list[str] = []
    if data.get("version") != 1:
        errors.append("matrix version must be 1")
    rows = data.get("case")
    if not isinstance(rows, list) or len(rows) != 7:
        return errors + ["case must contain the seven coherent RFC-3 positions"]
    required = {"id", *FIELDS, "engineer_label"}
    for row in rows:
        if not isinstance(row, dict) or set(row) != required:
            errors.append("every row must contain exactly the authoritative fields plus engineer_label")
    if errors:
        return errors
    ids = [row["id"] for row in rows]
    if len(ids) != len(set(ids)):
        errors.append("case ids must be unique")
    exact = {
        "scope": {"none", "per_execution", "bounded:8", "all"},
        "refutation": {"none", "abort", "trace:8", "incomplete", "complete", "empirical"},
        "residual_trust": {"fiat", "solver", "lean_checked"},
        "boundary_kind": {"end_to_end", "to_boundary", "to_platform"},
        "classification_verdict": {"admitted", "rejected", "unknown"},
        "policy_point": {"runtime", "bounded", "solver_complete", "lean_empirical"},
    }
    for field, expected in exact.items():
        actual = {row[field] for row in rows}
        if actual != expected:
            errors.append(f"{field} coverage mismatch: {sorted(actual)}")
    for source, needles in {
        "forge/src/manifest.rs": ["CertificationPosition", "ClassificationCertificate"],
        "forge/src/rfc3_replay.rs": ["FormalReplay", "engineer_label_is_structurally_non_authoritative"],
    }.items():
        text = (root / source).read_text(encoding="utf-8")
        for needle in needles:
            if needle not in text:
                errors.append(f"{source}: missing {needle}")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    try:
        data = json.loads((root / MATRIX).read_text(encoding="utf-8"))
        errors = validate(root, data)
        output = generated(data["case"]) if not errors else ""
        target = root / LEAN
        if args.write and not errors:
            target.write_text(output, encoding="utf-8")
        elif not errors and (not target.exists() or target.read_text(encoding="utf-8") != output):
            errors.append(f"{LEAN} is stale; run gates/rfc3-certification-replay.py --write")
    except (OSError, json.JSONDecodeError, KeyError, TypeError) as error:
        print(f"RFC-3 certification replay: INCONCLUSIVE: {error}", file=sys.stderr)
        return 3
    if errors:
        print("RFC-3 certification replay: FAIL", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1
    print("RFC-3 certification replay: clean: 7 positions, 14 authoritative mutation pins")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
