#!/usr/bin/env python3
"""Generate and check the shared Rust/Lean RFC-3 AC-10 replay boundary."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

MATRIX = "gates/rfc3-certification-replay.json"
LEAN = "lean/Thermite/CertificationReplay.lean"
FIELDS = [
    "scope", "refutation", "residual_trust", "discharged_trust",
    "boundary_kind", "boundary_value", "model_family", "model_version",
    "frame_semantics", "frame_version", "residual_context",
    "classification_fragment", "classification_verdict", "policy_point",
]

CANONICAL_FORMAL = {
    "no_claim": ["none", "none", "fiat", [], "end_to_end", "", "rustc", "1.95.0", "thermite-language", 1, "fiat", "thermite-core-v2", "admitted", "runtime"],
    "runtime": ["per_execution", "abort", "fiat", [], "to_boundary", "ffi::clock", "rustc", "1.95.0", "thermite-language", 1, "runtime and platform", "thermite-core-v2", "unknown", "runtime"],
    "bounded": ["bounded:8", "trace:8", "solver", [], "to_platform", "x86_64-unknown-linux-gnu", "rustc", "1.95.0", "thermite-language", 1, "solver and platform", "thermite-core-v2", "rejected", "bounded"],
    "incomplete_solver": ["all", "incomplete", "solver", [], "end_to_end", "", "rustc", "1.95.0", "thermite-language", 1, "solver", "thermite-core-v2", "admitted", "solver_complete"],
    "complete_solver": ["all", "complete", "solver", ["rustc:1.95.0"], "to_platform", "x86_64-unknown-linux-gnu", "rustc", "1.95.0", "thermite-language", 1, "checker and platform", "thermite-core-v2", "admitted", "solver_complete"],
    "empirical_lean": ["all", "empirical", "lean_checked", [], "to_boundary", "ffi::allocator", "rustc", "1.95.0", "thermite-language", 1, "kernel and boundary", "thermite-core-v2", "unknown", "lean_empirical"],
    "complete_lean": ["all", "complete", "lean_checked", ["solver", "rustc:1.95.0"], "end_to_end", "", "rustc", "1.95.0", "thermite-language", 1, "lean kernel", "thermite-core-v2", "admitted", "lean_empirical"],
}


def lean_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def lean_list(values: list[str]) -> str:
    return "[" + ", ".join(lean_string(value) for value in values) + "]"


def row_expr(row: dict[str, object]) -> str:
    parts = []
    for field in ["id", *FIELDS, "engineer_label"]:
        value = row[field]
        rendered = str(value) if isinstance(value, int) else lean_list(value) if isinstance(value, list) else lean_string(value)
        parts.append(f"    {field} := {rendered}")
    return "  {\n" + "\n".join(parts) + " }"


def generated(rows: list[dict[str, object]]) -> str:
    values = ",\n".join(row_expr(row) for row in rows)
    return f'''/- This file is generated by gates/rfc3-certification-replay.py. -/
import Thermite.CertificationReplaySemantics
import Thermite.TcbDischarge

namespace Thermite.CertificationMetatheory

structure CertificationReplayRow where
  id : String
  scope : String
  refutation : String
  residual_trust : String
  discharged_trust : List String
  boundary_kind : String
  boundary_value : String
  model_family : String
  model_version : String
  frame_semantics : String
  frame_version : Nat
  residual_context : String
  classification_fragment : String
  classification_verdict : String
  policy_point : String
  engineer_label : String
deriving DecidableEq, Repr, Inhabited

structure RawReplayProjection where
  scope : String
  refutation : String
  residual_trust : String
  discharged_trust : List String
  boundary_kind : String
  boundary_value : String
  model_family : String
  model_version : String
  frame_semantics : String
  frame_version : Nat
  residual_context : String
  classification_fragment : String
  classification_verdict : String
  policy_point : String
deriving DecidableEq, Repr

def CertificationReplayRow.formal (row : CertificationReplayRow) : RawReplayProjection :=
  ⟨row.scope, row.refutation, row.residual_trust, row.discharged_trust,
    row.boundary_kind, row.boundary_value, row.model_family, row.model_version,
    row.frame_semantics, row.frame_version, row.residual_context,
    row.classification_fragment, row.classification_verdict, row.policy_point⟩

def certificationReplaysAs (candidate expected : CertificationReplayRow) : Bool :=
  decide (candidate.formal = expected.formal)

def generatedCertificationReplay : List CertificationReplayRow := [
{values}
]

def semanticProjectionForId : String → Option FormalReplayProjection
  | "no_claim" => some ⟨.noClaim, .none, .none, .fiat, [], .endToEnd,
      rustc195Identity, ⟨"thermite-language", 1⟩, "fiat",
      ⟨"thermite-core", 2⟩, .admitted, .runtime⟩
  | "runtime" => some ⟨.runtime, .perExecution, .abort, .fiat, [],
      .toBoundary "ffi::clock", rustc195Identity, ⟨"thermite-language", 1⟩,
      "runtime and platform", ⟨"thermite-core", 2⟩, .unknown, .runtime⟩
  | "bounded" => some (boundedProjection 8)
  | "incomplete_solver" => some ⟨.incompleteSolver, .all, .incomplete, .solver, [],
      .endToEnd, rustc195Identity, ⟨"thermite-language", 1⟩, "solver",
      ⟨"thermite-core", 2⟩, .admitted, .solverComplete⟩
  | "complete_solver" => some ⟨.completeSolver, .all, .complete, .solver,
      ["rustc:1.95.0"], .toPlatform "x86_64-unknown-linux-gnu", rustc195Identity,
      ⟨"thermite-language", 1⟩, "checker and platform",
      ⟨"thermite-core", 2⟩, .admitted, .solverComplete⟩
  | "empirical_lean" => some ⟨.empiricalLean, .all, .empirical, .leanChecked, [],
      .toBoundary "ffi::allocator", rustc195Identity, ⟨"thermite-language", 1⟩,
      "kernel and boundary", ⟨"thermite-core", 2⟩, .unknown, .leanEmpirical⟩
  | "complete_lean" => some ⟨.completeLean, .all, .complete, .leanChecked,
      ["solver", "rustc:1.95.0"], .endToEnd, rustc195Identity,
      ⟨"thermite-language", 1⟩, "lean kernel",
      ⟨"thermite-core", 2⟩, .admitted, .leanEmpirical⟩
  | _ => none

def expectedRow (id : String) : Option CertificationReplayRow :=
  generatedCertificationReplay.find? (fun row => row.id == id)

/-- Decode succeeds only when every authoritative interchange field equals the
checked canonical row, then returns typed metatheory objects for that family. -/
def decodeCertificationReplay (row : CertificationReplayRow) : Option FormalReplayProjection :=
  match expectedRow row.id, semanticProjectionForId row.id with
  | some expected, some semantic =>
      if row.formal = expected.formal then some semantic else none
  | _, _ => none

def replayRowWellFormed (row : CertificationReplayRow) : Bool :=
  match decodeCertificationReplay row with
  | some semantic => coherentProjection semantic
  | none => false

def completeSolverReplay : CertificationReplayRow := generatedCertificationReplay[4]!

theorem every_generated_row_is_formally_well_formed :
    generatedCertificationReplay.all replayRowWellFormed = true := by decide

theorem generated_rows_cover_every_certification_family :
    generatedCertificationReplay.filterMap
      (fun row => (decodeCertificationReplay row).map FormalReplayProjection.cell) =
      allCertificationCells := by decide

theorem generated_rows_construct_actual_metatheory_objects :
    generatedCertificationReplay.all (fun row =>
      match decodeCertificationReplay row with
      | some semantic =>
          semantic.frame.semantics == "thermite-language" &&
          semantic.model == rustc195Identity &&
          semantic.fragment.version == ⟨"thermite-core", 2⟩ &&
          !semantic.context.name.isEmpty
      | none => false) = true := by decide

def authoritativeMutations : List CertificationReplayRow := [
  {{ completeSolverReplay with scope := "none" }},
  {{ completeSolverReplay with refutation := "incomplete" }},
  {{ completeSolverReplay with residual_trust := "fiat" }},
  {{ completeSolverReplay with discharged_trust := ["engineer-label"] }},
  {{ completeSolverReplay with boundary_kind := "to_boundary" }},
  {{ completeSolverReplay with boundary_value := "engineer-label" }},
  {{ completeSolverReplay with model_family := "engineer-label" }},
  {{ completeSolverReplay with model_version := "1.96.0" }},
  {{ completeSolverReplay with frame_semantics := "engineer-label" }},
  {{ completeSolverReplay with frame_version := 2 }},
  {{ completeSolverReplay with residual_context := "engineer-label" }},
  {{ completeSolverReplay with classification_fragment := "engineer-label" }},
  {{ completeSolverReplay with classification_verdict := "unknown" }},
  {{ completeSolverReplay with policy_point := "lean_empirical" }}
]

theorem every_authoritative_mutation_is_rejected :
    authoritativeMutations.all (fun row => (decodeCertificationReplay row).isNone) = true := by
  decide

def relabeledReplay : CertificationReplayRow :=
  {{ completeSolverReplay with engineer_label := "anything presentational" }}

theorem engineer_label_is_non_authoritative :
    decodeCertificationReplay relabeledReplay = decodeCertificationReplay completeSolverReplay := by decide

def engineerLabelSubstitutedForFormalScope : CertificationReplayRow :=
  {{ completeSolverReplay with scope := completeSolverReplay.engineer_label }}

theorem engineer_label_formal_substitution_rejected :
    decodeCertificationReplay engineerLabelSubstitutedForFormalScope = none := by
  decide

end Thermite.CertificationMetatheory
'''


def validate(root: Path, data: dict[str, object]) -> list[str]:
    errors: list[str] = []
    if data.get("version") != 1:
        errors.append("matrix version must be 1")
    rows = data.get("case")
    if not isinstance(rows, list) or len(rows) != 7:
        return errors + ["case must contain the seven coherent RFC-3 positions"]
    required = {"id", *FIELDS, "engineer_label"}
    for row in rows:
        if not isinstance(row, dict) or set(row) != required:
            errors.append("every row must contain exactly the authoritative fields plus engineer_label")
    if errors:
        return errors
    ids = [row["id"] for row in rows]
    if len(ids) != len(set(ids)):
        errors.append("case ids must be unique")
    if ids != list(CANONICAL_FORMAL):
        errors.append("case ids/order must equal the seven canonical certification families")
    for row in rows:
        expected = CANONICAL_FORMAL.get(row["id"])
        actual = [row[field] for field in FIELDS]
        if expected is not None and actual != expected:
            errors.append(f"{row['id']}: authoritative mapping differs from the canonical family")
    exact = {
        "scope": {"none", "per_execution", "bounded:8", "all"},
        "refutation": {"none", "abort", "trace:8", "incomplete", "complete", "empirical"},
        "residual_trust": {"fiat", "solver", "lean_checked"},
        "boundary_kind": {"end_to_end", "to_boundary", "to_platform"},
        "classification_verdict": {"admitted", "rejected", "unknown"},
        "policy_point": {"runtime", "bounded", "solver_complete", "lean_empirical"},
    }
    for field, expected in exact.items():
        actual = {row[field] for row in rows}
        if actual != expected:
            errors.append(f"{field} coverage mismatch: {sorted(actual)}")
    for source, needles in {
        "forge/src/manifest.rs": ["CertificationPosition", "ClassificationCertificate"],
        "forge/src/rfc3_replay.rs": ["FormalReplay", "engineer_label_is_structurally_non_authoritative"],
    }.items():
        text = (root / source).read_text(encoding="utf-8")
        for needle in needles:
            if needle not in text:
                errors.append(f"{source}: missing {needle}")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    try:
        data = json.loads((root / MATRIX).read_text(encoding="utf-8"))
        errors = validate(root, data)
        output = generated(data["case"]) if not errors else ""
        target = root / LEAN
        if args.write and not errors:
            target.write_text(output, encoding="utf-8")
        elif not errors and (not target.exists() or target.read_text(encoding="utf-8") != output):
            errors.append(f"{LEAN} is stale; run gates/rfc3-certification-replay.py --write")
    except (OSError, json.JSONDecodeError, KeyError, TypeError) as error:
        print(f"RFC-3 certification replay: INCONCLUSIVE: {error}", file=sys.stderr)
        return 3
    if errors:
        print("RFC-3 certification replay: FAIL", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1
    print("RFC-3 certification replay: clean: 7 positions, 14 authoritative mutation pins")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
