#!/usr/bin/env python3
"""Validate and generate the workspace/build-matrix assurance replay."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

MATRIX = "gates/workspace-assurance-replay.json"
LEAN = "lean/Thermite/WorkspaceCompositionReplay.lean"
OUTCOMES = {"whole_workspace", "accepted_subset", "rejected"}


def classify(case: dict[str, object]) -> str:
    if not (
        case["plan_exact"] is True
        and case["coordinates_unique"] is True
        and case["items_exact"] is True
    ):
        return "rejected"
    if (
        case["all_reports"] is True
        and case["all_project_lifts"] is True
        and case["nonempty"] is True
    ):
        return "whole_workspace"
    return "accepted_subset"


def lean_outcome(value: str) -> str:
    pieces = value.split("_")
    return "." + pieces[0] + "".join(piece.title() for piece in pieces[1:])


def generated(cases: list[dict[str, object]]) -> str:
    rows = []
    for case in cases:
        flags = ", ".join(
            str(case[field]).lower()
            for field in (
                "plan_exact",
                "coordinates_unique",
                "all_reports",
                "items_exact",
                "all_project_lifts",
                "nonempty",
            )
        )
        rows.append(
            f"  ⟨{json.dumps(case['id'])}, {flags}, {lean_outcome(str(case['outcome']))}⟩"
        )
    body = ",\n".join(rows)
    return f'''/- This file is generated by gates/workspace-assurance-replay.py. -/
import Thermite.WorkspaceComposition

namespace Thermite.CertificationMetatheory

inductive WorkspaceReplayOutcome where
  | wholeWorkspace | acceptedSubset | rejected
deriving DecidableEq, Repr

structure WorkspaceReplayCase where
  id : String
  planExact : Bool
  coordinatesUnique : Bool
  allReports : Bool
  itemsExact : Bool
  allProjectLifts : Bool
  nonempty : Bool
  expected : WorkspaceReplayOutcome
deriving DecidableEq, Repr

def classifyWorkspaceReplay (row : WorkspaceReplayCase) : WorkspaceReplayOutcome :=
  if !row.planExact || !row.coordinatesUnique || !row.itemsExact then .rejected
  else if row.allReports && row.allProjectLifts && row.nonempty then .wholeWorkspace
  else .acceptedSubset

def WorkspaceReplayCase.accepts (row : WorkspaceReplayCase) : Bool :=
  decide (classifyWorkspaceReplay row = row.expected)

def generatedWorkspaceReplayCases : List WorkspaceReplayCase := [
{body}
]

theorem generated_workspace_replay_matches_checked_composition :
    generatedWorkspaceReplayCases.all WorkspaceReplayCase.accepts = true := by
  decide

theorem generated_workspace_replay_covers_ten_cases_and_three_outcomes :
    generatedWorkspaceReplayCases.length = 10 ∧
      (generatedWorkspaceReplayCases.map fun row => row.expected).eraseDups.length = 3 := by
  decide

def omittedItemAcceptedMutant : List WorkspaceReplayCase :=
  generatedWorkspaceReplayCases.map fun row =>
    if row.id = "planned-item-omitted" then {{ row with expected := .wholeWorkspace }} else row

theorem omitted_item_accepted_mutant_is_rejected :
    omittedItemAcceptedMutant.all WorkspaceReplayCase.accepts = false := by
  decide

end Thermite.CertificationMetatheory
'''


def validate(root: Path) -> list[str]:
    data = json.loads((root / MATRIX).read_text(encoding="utf-8"))
    errors: list[str] = []
    if data.get("version") != 1:
        errors.append("matrix version must be 1")
    if set(data.get("outcomes", [])) != OUTCOMES:
        errors.append("matrix outcomes must cover whole_workspace, accepted_subset, and rejected")
    cases = data.get("case")
    if not isinstance(cases, list) or len(cases) != 10:
        errors.append("matrix must contain exactly ten named cases")
        return errors
    ids = [case.get("id") for case in cases]
    if len(ids) != len(set(ids)):
        errors.append("case IDs must be unique")
    for case in cases:
        if classify(case) != case.get("outcome"):
            errors.append(f"{case.get('id')}: outcome does not match checked rule")
    if {case.get("outcome") for case in cases} != OUTCOMES:
        errors.append("cases must exercise all three outcomes")
    target = root / LEAN
    if not target.exists() or target.read_text(encoding="utf-8") != generated(cases):
        errors.append(f"{LEAN} is stale; run {Path(__file__).name} --write")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    data = json.loads((root / MATRIX).read_text(encoding="utf-8"))
    cases = data.get("case", [])
    if args.write:
        (root / LEAN).write_text(generated(cases), encoding="utf-8")
    errors = validate(root)
    if errors:
        for error in errors:
            print(f"workspace-assurance-replay: {error}", file=sys.stderr)
        return 1
    print(f"workspace-assurance-replay: {len(cases)} checked cases")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
