//! SPIKE-2 — the normalizer-probe hit-rate target + fixture verifier
//! (`.design/m0-spikes.md` REQ-7 / AC-5 / AC-7).
//!
//! This is the read-only half of the spike's "test/bin target" (REQ-7): the
//! committed fixtures under `tests/fixtures/strat_probe/` are (re)generated by the
//! `strat_probe` example; this test reads them back, re-runs the prototype
//! normalizer (`thermite_tv::normalize`, the spike's only pipeline-external
//! consumer — AC-6), and asserts:
//!
//! - every fixture's two raw-quantifier spellings parse (AC-5);
//! - the recomputed hit matches the `hit:` recorded in each file, so the
//!   committed artifacts can never silently drift from the normalizer code;
//! - there are the 4 named corpus pairs + ≥5 generator-drawn pairs per shape,
//!   yielding ≥30 total (AC-5);
//! - the corpus-only (n=4) + corpus+generated rates + per-shape breakdown +
//!   decision branch recomputed here match the numbers recorded in the fixtures
//!   `README.md` (AC-7) — the README is a tested artifact, not free text.

use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;

use thermite_tv::normalize;

/// One parsed fixture file.
struct Fixture {
    shape: String,
    source: String,
    origin: String,
    recorded_hit: bool,
    production: String,
    reference: String,
}

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/strat_probe")
}

fn parse_fixture(text: &str, path: &str) -> Fixture {
    let mut shape = None;
    let mut source = None;
    let mut origin = None;
    let mut recorded_hit = None;
    let mut production = String::new();
    let mut reference = String::new();
    let mut section = 0u8; // 0 = headers, 1 = production, 2 = reference
    for line in text.lines() {
        match line.trim() {
            "--- production ---" => {
                section = 1;
                continue;
            }
            "--- reference ---" => {
                section = 2;
                continue;
            }
            _ => {}
        }
        match section {
            0 => {
                if let Some(v) = line.strip_prefix("shape:") {
                    shape = Some(v.trim().to_string());
                } else if let Some(v) = line.strip_prefix("source:") {
                    source = Some(v.trim().to_string());
                } else if let Some(v) = line.strip_prefix("origin:") {
                    origin = Some(v.trim().to_string());
                } else if let Some(v) = line.strip_prefix("hit:") {
                    recorded_hit = Some(v.trim() == "true");
                }
            }
            1 => {
                if !line.starts_with('#') {
                    production.push_str(line);
                }
            }
            _ => {
                if !line.starts_with('#') {
                    reference.push_str(line);
                }
            }
        }
    }
    Fixture {
        shape: shape.unwrap_or_else(|| panic!("{path}: no shape header")),
        source: source.unwrap_or_else(|| panic!("{path}: no source header")),
        origin: origin.unwrap_or_else(|| panic!("{path}: no origin header")),
        recorded_hit: recorded_hit.unwrap_or_else(|| panic!("{path}: no hit header")),
        production: production.trim().to_string(),
        reference: reference.trim().to_string(),
    }
}

fn load_fixtures() -> Vec<Fixture> {
    let dir = fixtures_dir();
    let mut out = Vec::new();
    let mut paths: Vec<_> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", dir.display()))
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().map(|x| x == "fixture").unwrap_or(false))
        .collect();
    paths.sort();
    for p in paths {
        let text = fs::read_to_string(&p).expect("read fixture");
        out.push(parse_fixture(&text, &p.display().to_string()));
    }
    out
}

fn pct(h: usize, t: usize) -> f64 {
    if t == 0 {
        0.0
    } else {
        100.0 * h as f64 / t as f64
    }
}

/// AC-5: every fixture parses, and the recomputed hit matches the `hit:` recorded
/// in the file (the committed artifacts cannot drift from the normalizer code).
#[test]
fn every_fixture_parses_and_its_recorded_hit_matches_the_normalizer() {
    let fixtures = load_fixtures();
    assert!(!fixtures.is_empty(), "no fixtures found");
    for f in &fixtures {
        let result = normalize::pair_hits(&f.production, &f.reference).unwrap_or_else(|e| {
            panic!(
                "{} ({}): fixture failed to parse: {e}\n  prod: {}\n  ref:  {}",
                f.source, f.shape, f.production, f.reference
            )
        });
        assert_eq!(
            result.hit, f.recorded_hit,
            "{} ({}): recorded hit={} but normalizer says {}\n  prod canonical: {}\n  ref  canonical: {}",
            f.source, f.shape, f.recorded_hit, result.hit, result.production_canonical, result.reference_canonical
        );
    }
}

/// AC-5: the 4 named `binary_search.th` corpus pairs are present (with their
/// scheme-validated / informal sources), each appearing combinator shape has both
/// spellings, ≥5 generator-drawn pairs exist per shape, and the total is ≥30.
#[test]
fn corpus_and_generated_coverage_meets_ac5() {
    let fixtures = load_fixtures();

    // The 4 corpus clauses, by (shape, source).
    let corpus: Vec<(&str, &str)> = fixtures
        .iter()
        .filter(|f| f.origin == "corpus")
        .map(|f| (f.shape.as_str(), f.source.as_str()))
        .collect();
    let expected_corpus = [
        ("sorted", "binary_search.requires"),
        ("forall_in", "binary_search.ensures.None"),
        ("forall_below", "binary_search.loop#1.keeps#2"),
        ("forall_from", "binary_search.loop#1.keeps#3"),
    ];
    for ec in expected_corpus {
        assert!(
            corpus.contains(&ec),
            "missing corpus fixture {ec:?}; have {corpus:?}"
        );
    }
    assert_eq!(
        corpus.len(),
        4,
        "exactly the 4 binary_search corpus clauses"
    );

    // ≥5 generator-drawn pairs per appearing shape.
    let mut gen_by_shape: BTreeMap<String, usize> = BTreeMap::new();
    for f in &fixtures {
        if f.origin == "generated" {
            *gen_by_shape.entry(f.shape.clone()).or_default() += 1;
        }
    }
    assert!(!gen_by_shape.is_empty(), "no generated fixtures");
    for (shape, count) in &gen_by_shape {
        assert!(
            *count >= 5,
            "shape {shape}: only {count} generator-drawn pairs (< 5, AC-5)"
        );
    }

    assert!(
        fixtures.len() >= 30,
        "only {} fixture pairs (< ~30 threshold-bearing denominator, AC-5)",
        fixtures.len()
    );
}

/// AC-7: the corpus-only (n=4, small-n) and corpus+generated (threshold-bearing)
/// hit rates + per-shape breakdown + decision branch recomputed from the fixtures
/// match the numbers recorded in the fixtures `README.md`.
#[test]
fn hit_rates_match_the_readme_record() {
    let fixtures = load_fixtures();
    let readme = fs::read_to_string(fixtures_dir().join("README.md")).expect("read README");

    let (mut ch, mut ct, mut ah, mut at) = (0usize, 0usize, 0usize, 0usize);
    let mut by_shape: BTreeMap<String, (usize, usize)> = BTreeMap::new();
    for f in &fixtures {
        let hit = normalize::pair_hits(&f.production, &f.reference)
            .unwrap()
            .hit as usize;
        at += 1;
        ah += hit;
        if f.origin == "corpus" {
            ct += 1;
            ch += hit;
        }
        let e = by_shape.entry(f.shape.clone()).or_insert((0, 0));
        e.0 += hit;
        e.1 += 1;
    }

    assert_eq!(ct, 4, "corpus-only n must be 4 (AC-7 small-n number)");

    // The two rate lines, formatted as the README writes them.
    let corpus_line = format!(
        "(n={ct}, **small-n**, NOT threshold-bearing on its own): **{ch}/{ct} = {:.1}%**",
        pct(ch, ct)
    );
    let all_line = format!(
        "(n={at}, **threshold-bearing**): **{ah}/{at} = {:.1}%**",
        pct(ah, at)
    );
    assert!(
        readme.contains(&corpus_line),
        "README missing recomputed corpus-only line: `{corpus_line}`"
    );
    assert!(
        readme.contains(&all_line),
        "README missing recomputed corpus+generated line: `{all_line}`"
    );

    // The per-shape breakdown rows.
    for (shape, (h, t)) in &by_shape {
        let row = format!("| `{shape}` | {h}/{t} | {:.1}% |", pct(*h, *t));
        assert!(
            readme.contains(&row),
            "README missing per-shape row: `{row}`"
        );
    }

    // The decision branch, applied to the threshold-bearing rate.
    let decision_ships = pct(ah, at) >= 90.0;
    if decision_ships {
        assert!(
            readme.contains("thin fallback"),
            "rate ≥ 90% but README does not record the thin-fallback branch"
        );
    } else {
        assert!(
            readme.contains("quantified-equivalence"),
            "rate < 90% but README does not record the design-issue branch"
        );
    }
}
