//! Algebraic denotations for the closed surface [`Effect`] vocabulary.
//!
//! Governing design: `.design/syntax/effect-algebra.md`. This module is an
//! additive analysis beside the existing effect mask: it preserves region
//! instances and operation sets so later checks can derive frame conditions,
//! footprints, and commutation facts.
//!
//! ## REQ status
//!
//! | REQ | Status | Evidence |
//! |---|---|---|
//! | REQ-1 | SHIPPED | [`Theory::frame_condition`] generates the admissibility witness. |
//! | REQ-2 | SHIPPED | [`Theory`] contains the five closed basis theories. |
//! | REQ-3 | SHIPPED | [`GivenAtom`] records `random` and `blocks` outside the basis. |
//! | REQ-4 | SHIPPED | [`Entry`] pairs a theory instance with its capability operations. |
//! | REQ-5 | SHIPPED | [`entry_for_effect`] exhaustively maps all nine [`Effect`] variants. |
//! | REQ-6 | SHIPPED | [`BasisEntry::Combination`] represents `net` as state plus free I/O. |
//! | REQ-7 | SHIPPED | `EffectDeclItem`, the parser, and [`resolve_declaration`] close declarations over the five primitives. |
//! | REQ-8 | SHIPPED | `thermite_spec::effect_commutation` computes facts from these entries. |
//! | REQ-9 | SHIPPED | `thermite_lower::LowerError::EffectNotSubsumed` reports [`entry_for_effect`] and its frame condition without changing the missing set. |
//! | REQ-10 | SHIPPED | RFC-9's production consumer checks region overlap and computed commutation in `thermite_spec::effect_commutation`. |
//! | REQ-11 | SHIPPED | This module does not alter `Effect`, lowering masks, or verified subsumption. |
//! | REQ-12 | SHIPPED | [`BasisEntry::footprint`] projects region reads and writes. |
//! | REQ-13 | SHIPPED | [`route_for_effect`] and [`route_for_given`] provide discharge classifications. |
//! | REQ-14 | SHIPPED | RFC-9's production conflict consumer is wired through `thermite_spec::effect_commutation`. |

use std::collections::BTreeSet;

use crate::ast::{Effect, EffectDeclItem, EffectPrimitive};

/// A named instance parameter carried by a theory.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct Instance(pub String);

impl Instance {
    fn named(name: &str) -> Self {
        Self(name.to_owned())
    }
}

/// The closed five-theory effect basis (REQ-2).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Theory {
    State(Instance),
    Accrues(String),
    Exception,
    Partiality,
    Io(String),
}

impl Theory {
    /// Generate the primitive's frame condition (REQ-1/REQ-2).
    pub fn frame_condition(&self) -> FrameCondition {
        match self {
            Self::State(instance) => FrameCondition::MayModifyOnly(instance.clone()),
            Self::Accrues(monoid) => FrameCondition::GhostAccumulator(monoid.clone()),
            Self::Exception => FrameCondition::MayNotReturnNormally,
            Self::Partiality => FrameCondition::MayNotReturn,
            Self::Io(signature) => FrameCondition::UnconstrainedValueNoRegion(signature.clone()),
        }
    }
}

/// A prover-expressible frame condition generated by the basis.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FrameCondition {
    MayModifyOnly(Instance),
    GhostAccumulator(String),
    MayNotReturnNormally,
    MayNotReturn,
    UnconstrainedValueNoRegion(String),
    Conjunction(Vec<FrameCondition>),
}

/// Atoms intentionally outside the five-theory basis (REQ-3).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GivenAtom {
    Random,
    Blocks,
}

/// Operations a row entry may perform (REQ-4).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Operation {
    Get,
    Put,
    Accrue,
    Raise,
    FailToTerminate,
    InvokeIo,
}

/// One instantiated theory and the upper bound on operations it permits.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Entry {
    pub theory: Theory,
    pub operations: BTreeSet<Operation>,
}

impl Entry {
    fn state(region: &str, operations: impl IntoIterator<Item = Operation>) -> Self {
        Self {
            theory: Theory::State(Instance::named(region)),
            operations: operations.into_iter().collect(),
        }
    }

    fn io(signature: &str) -> Self {
        Self {
            theory: Theory::Io(signature.to_owned()),
            operations: [Operation::InvokeIo].into_iter().collect(),
        }
    }

    fn operationless(theory: Theory) -> Self {
        Self {
            theory,
            operations: BTreeSet::new(),
        }
    }
}

/// The denotation of one surface label: one entry or a conservative sum.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BasisEntry {
    Primitive(Entry),
    Combination(Vec<Entry>),
}

impl BasisEntry {
    /// Generate this entry's frame condition, conjoining combination summands.
    pub fn frame_condition(&self) -> FrameCondition {
        match self {
            Self::Primitive(entry) => entry.theory.frame_condition(),
            Self::Combination(entries) => FrameCondition::Conjunction(
                entries
                    .iter()
                    .map(|entry| entry.theory.frame_condition())
                    .collect(),
            ),
        }
    }

    /// Derive the regions this entry may read and write (REQ-12).
    pub fn footprint(&self) -> Footprint {
        let mut footprint = Footprint::default();
        let entries: &[Entry] = match self {
            Self::Primitive(entry) => std::slice::from_ref(entry),
            Self::Combination(entries) => entries,
        };

        for entry in entries {
            match &entry.theory {
                Theory::State(instance) => {
                    if entry.operations.contains(&Operation::Get) {
                        footprint.reads.insert(instance.clone());
                    }
                    if entry.operations.contains(&Operation::Put) {
                        footprint.writes.insert(instance.clone());
                    }
                }
                Theory::Io(_) => footprint.carries_io = true,
                Theory::Accrues(_) | Theory::Exception | Theory::Partiality => {}
            }
        }
        footprint
    }
}

/// Region projection of an effect entry.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Footprint {
    pub reads: BTreeSet<Instance>,
    pub writes: BTreeSet<Instance>,
    pub carries_io: bool,
}

/// Premise under which no further characteristic obligation remains.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NoObligationPremise {
    None,
    RowChecked,
}

/// A known witness form for an effect's characteristic obligation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DischargeForm {
    Measures,
    SessionDuality,
}

/// An obligation whose sound discharge form is not yet known.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DischargeQuestion {
    RandomTheory,
}

/// How an effect's characteristic obligation is discharged (REQ-13).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ObligationRoute {
    NoObligation(NoObligationPremise),
    Implemented(DischargeForm),
    Deferred(DischargeForm),
    Open(DischargeQuestion),
}

/// Resolve every current surface effect to its algebraic entry (REQ-5).
pub fn entry_for_effect(effect: &Effect) -> BasisEntry {
    let state_read = |region: &str| Entry::state(region, [Operation::Get]);
    let state_write = |region: &str| Entry::state(region, [Operation::Get, Operation::Put]);

    match effect {
        Effect::Read(region) => BasisEntry::Primitive(state_read(&region.display())),
        Effect::Write(region) => BasisEntry::Primitive(state_write(&region.display())),
        Effect::Net(domain) => BasisEntry::Combination(vec![
            state_write(&domain.display()),
            Entry::io(&format!("sigma_{domain}")),
        ]),
        // Acquisition is a checked stateful effect over the symbolic lock
        // instance. RFC-10's compatibility consumer distinguishes holder/holder
        // serialization from ordinary state writes.
        Effect::Owns(lock) => BasisEntry::Primitive(state_write(&format!("lock:{lock}"))),
        Effect::Alloc => BasisEntry::Primitive(state_write("heap")),
        Effect::Time => BasisEntry::Primitive(state_read("clock")),
        Effect::Rand => BasisEntry::Primitive(state_write("entropy")),
        Effect::Panic => BasisEntry::Primitive(Entry::operationless(Theory::Exception)),
        Effect::Diverge => BasisEntry::Primitive(Entry::operationless(Theory::Partiality)),
        Effect::Term => BasisEntry::Primitive(state_write("termios")),
    }
}

/// Resolve a parsed declaration to basis primitives before lowering (REQ-7).
pub fn resolve_declaration(declaration: &EffectDeclItem) -> BasisEntry {
    let entries = declaration
        .combination
        .iter()
        .map(|primitive| match primitive {
            EffectPrimitive::State(instance) => {
                Entry::state(instance, [Operation::Get, Operation::Put])
            }
            EffectPrimitive::Accrues(monoid) => Entry {
                theory: Theory::Accrues(monoid.clone()),
                operations: [Operation::Accrue].into_iter().collect(),
            },
            EffectPrimitive::Exception => Entry {
                theory: Theory::Exception,
                operations: [Operation::Raise].into_iter().collect(),
            },
            EffectPrimitive::Partiality => Entry {
                theory: Theory::Partiality,
                operations: [Operation::FailToTerminate].into_iter().collect(),
            },
            EffectPrimitive::Io(signature) => Entry::io(signature),
        })
        .collect::<Vec<_>>();

    match entries.as_slice() {
        [entry] => BasisEntry::Primitive(entry.clone()),
        _ => BasisEntry::Combination(entries),
    }
}

/// Classify the discharge route for every current surface effect.
pub const fn route_for_effect(effect: &Effect) -> ObligationRoute {
    match effect {
        Effect::Panic => ObligationRoute::NoObligation(NoObligationPremise::None),
        Effect::Diverge => ObligationRoute::Implemented(DischargeForm::Measures),
        Effect::Read(_)
        | Effect::Write(_)
        | Effect::Net(_)
        | Effect::Owns(_)
        | Effect::Alloc
        | Effect::Time
        | Effect::Rand
        | Effect::Term => ObligationRoute::NoObligation(NoObligationPremise::RowChecked),
    }
}

/// Classify routes for reserved atoms that have no surface label yet.
pub const fn route_for_given(atom: GivenAtom) -> ObligationRoute {
    match atom {
        GivenAtom::Blocks => ObligationRoute::Deferred(DischargeForm::SessionDuality),
        GivenAtom::Random => ObligationRoute::Open(DischargeQuestion::RandomTheory),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn set(values: &[&str]) -> BTreeSet<Instance> {
        values.iter().map(|value| Instance::named(value)).collect()
    }

    #[test]
    fn all_surface_labels_have_the_contractual_basis_entry() {
        let cases = [
            (Effect::Read("r".into()), set(&["r"]), set(&[]), false),
            (Effect::Write("r".into()), set(&["r"]), set(&["r"]), false),
            (Effect::Net("d".into()), set(&["d"]), set(&["d"]), true),
            (Effect::Alloc, set(&["heap"]), set(&["heap"]), false),
            (Effect::Time, set(&["clock"]), set(&[]), false),
            (Effect::Rand, set(&["entropy"]), set(&["entropy"]), false),
            (Effect::Panic, set(&[]), set(&[]), false),
            (Effect::Diverge, set(&[]), set(&[]), false),
            (Effect::Term, set(&["termios"]), set(&["termios"]), false),
        ];

        for (effect, reads, writes, carries_io) in cases {
            assert_eq!(
                entry_for_effect(&effect).footprint(),
                Footprint {
                    reads,
                    writes,
                    carries_io,
                }
            );
        }
    }

    #[test]
    fn read_and_write_operation_sets_match_the_contract() {
        let BasisEntry::Primitive(read) = entry_for_effect(&Effect::Read("r".into())) else {
            unreachable!();
        };
        let BasisEntry::Primitive(write) = entry_for_effect(&Effect::Write("r".into())) else {
            unreachable!();
        };
        assert_eq!(read.theory, write.theory);
        assert_eq!(read.operations, [Operation::Get].into_iter().collect());
        assert_eq!(
            write.operations,
            [Operation::Get, Operation::Put].into_iter().collect()
        );
    }

    #[test]
    fn net_is_state_plus_free_io() {
        let net = entry_for_effect(&Effect::Net("db".into()));
        let BasisEntry::Combination(entries) = &net else {
            unreachable!();
        };
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[0].theory, Theory::State(Instance::named("db")));
        assert_eq!(entries[1].theory, Theory::Io("sigma_db".into()));
        assert_eq!(
            net.frame_condition(),
            FrameCondition::Conjunction(vec![
                FrameCondition::MayModifyOnly(Instance::named("db")),
                FrameCondition::UnconstrainedValueNoRegion("sigma_db".into()),
            ])
        );
    }

    #[test]
    fn footprint_and_label_mask_membership_agree() {
        let cases = [
            (Effect::Read("r".into()), true, false),
            (Effect::Write("r".into()), true, true),
            (Effect::Net("d".into()), true, true),
            (Effect::Alloc, true, true),
            (Effect::Time, true, false),
            (Effect::Rand, true, true),
            (Effect::Panic, false, false),
            (Effect::Diverge, false, false),
            (Effect::Term, true, true),
        ];
        for (effect, mask_reads, mask_writes) in cases {
            let footprint = entry_for_effect(&effect).footprint();
            assert_eq!(!footprint.reads.is_empty(), mask_reads);
            assert_eq!(!footprint.writes.is_empty(), mask_writes);
        }
    }

    #[test]
    fn routes_carry_their_premises_and_forms() {
        assert_eq!(
            route_for_effect(&Effect::Read("r".into())),
            ObligationRoute::NoObligation(NoObligationPremise::RowChecked)
        );
        assert_eq!(
            route_for_effect(&Effect::Panic),
            ObligationRoute::NoObligation(NoObligationPremise::None)
        );
        assert_eq!(
            route_for_effect(&Effect::Diverge),
            ObligationRoute::Implemented(DischargeForm::Measures)
        );
        assert_eq!(
            route_for_given(GivenAtom::Blocks),
            ObligationRoute::Deferred(DischargeForm::SessionDuality)
        );
        assert_eq!(
            route_for_given(GivenAtom::Random),
            ObligationRoute::Open(DischargeQuestion::RandomTheory)
        );
    }

    #[test]
    fn basis_is_closed_and_its_members_generate_frames() {
        let theories = [
            Theory::State(Instance::named("r")),
            Theory::Accrues("M".into()),
            Theory::Exception,
            Theory::Partiality,
            Theory::Io("sigma".into()),
        ];
        assert_eq!(
            theories
                .iter()
                .map(Theory::frame_condition)
                .collect::<Vec<_>>(),
            vec![
                FrameCondition::MayModifyOnly(Instance::named("r")),
                FrameCondition::GhostAccumulator("M".into()),
                FrameCondition::MayNotReturnNormally,
                FrameCondition::MayNotReturn,
                FrameCondition::UnconstrainedValueNoRegion("sigma".into()),
            ]
        );
    }
}
